; Generated by gfx.py. Do not edit.

; --- buildings, generated by gfx.py: drawbars_a the left half, _b the right ---
drawbars_a
        ldx barh+0
        cpx bard+0
        beq _skip0
        stx bard+0
        lda bartab0,x
        sta SCREEN+240
        lda bartab1,x
        sta SCREEN+280
        lda bartab2,x
        sta SCREEN+320
        lda bartab3,x
        sta SCREEN+360
        lda bartab4,x
        sta SCREEN+400
        lda bartab5,x
        sta SCREEN+440
        lda bartab6,x
        sta SCREEN+480
        lda bartab7,x
        sta SCREEN+241
        lda bartab8,x
        sta SCREEN+281
        lda bartab9,x
        sta SCREEN+321
        lda bartab10,x
        sta SCREEN+361
        lda bartab11,x
        sta SCREEN+401
        lda bartab12,x
        sta SCREEN+441
        lda bartab13,x
        sta SCREEN+481
_skip0
        ldx barh+1
        cpx bard+1
        beq _skip1
        stx bard+1
        lda bartab14,x
        sta SCREEN+242
        lda bartab15,x
        sta SCREEN+282
        lda bartab16,x
        sta SCREEN+322
        lda bartab17,x
        sta SCREEN+362
        lda bartab18,x
        sta SCREEN+402
        lda bartab19,x
        sta SCREEN+442
        lda bartab20,x
        sta SCREEN+482
        lda bartab21,x
        sta SCREEN+243
        lda bartab22,x
        sta SCREEN+283
        lda bartab23,x
        sta SCREEN+323
        lda bartab24,x
        sta SCREEN+363
        lda bartab25,x
        sta SCREEN+403
        lda bartab26,x
        sta SCREEN+443
        lda bartab27,x
        sta SCREEN+483
_skip1
        ldx barh+2
        cpx bard+2
        beq _skip2
        stx bard+2
        lda bartab0,x
        sta SCREEN+244
        lda bartab1,x
        sta SCREEN+284
        lda bartab2,x
        sta SCREEN+324
        lda bartab3,x
        sta SCREEN+364
        lda bartab4,x
        sta SCREEN+404
        lda bartab5,x
        sta SCREEN+444
        lda bartab6,x
        sta SCREEN+484
        lda bartab7,x
        sta SCREEN+245
        lda bartab8,x
        sta SCREEN+285
        lda bartab9,x
        sta SCREEN+325
        lda bartab10,x
        sta SCREEN+365
        lda bartab11,x
        sta SCREEN+405
        lda bartab12,x
        sta SCREEN+445
        lda bartab13,x
        sta SCREEN+485
_skip2
        ldx barh+3
        cpx bard+3
        beq _skip3
        stx bard+3
        lda bartab14,x
        sta SCREEN+246
        lda bartab15,x
        sta SCREEN+286
        lda bartab16,x
        sta SCREEN+326
        lda bartab17,x
        sta SCREEN+366
        lda bartab18,x
        sta SCREEN+406
        lda bartab19,x
        sta SCREEN+446
        lda bartab20,x
        sta SCREEN+486
        lda bartab21,x
        sta SCREEN+247
        lda bartab22,x
        sta SCREEN+287
        lda bartab23,x
        sta SCREEN+327
        lda bartab24,x
        sta SCREEN+367
        lda bartab25,x
        sta SCREEN+407
        lda bartab26,x
        sta SCREEN+447
        lda bartab27,x
        sta SCREEN+487
_skip3
        ldx barh+4
        cpx bard+4
        beq _skip4
        stx bard+4
        lda bartab0,x
        sta SCREEN+248
        lda bartab1,x
        sta SCREEN+288
        lda bartab2,x
        sta SCREEN+328
        lda bartab3,x
        sta SCREEN+368
        lda bartab4,x
        sta SCREEN+408
        lda bartab5,x
        sta SCREEN+448
        lda bartab6,x
        sta SCREEN+488
        lda bartab7,x
        sta SCREEN+249
        lda bartab8,x
        sta SCREEN+289
        lda bartab9,x
        sta SCREEN+329
        lda bartab10,x
        sta SCREEN+369
        lda bartab11,x
        sta SCREEN+409
        lda bartab12,x
        sta SCREEN+449
        lda bartab13,x
        sta SCREEN+489
_skip4
        ldx barh+5
        cpx bard+5
        beq _skip5
        stx bard+5
        lda bartab14,x
        sta SCREEN+250
        lda bartab15,x
        sta SCREEN+290
        lda bartab16,x
        sta SCREEN+330
        lda bartab17,x
        sta SCREEN+370
        lda bartab18,x
        sta SCREEN+410
        lda bartab19,x
        sta SCREEN+450
        lda bartab20,x
        sta SCREEN+490
        lda bartab21,x
        sta SCREEN+251
        lda bartab22,x
        sta SCREEN+291
        lda bartab23,x
        sta SCREEN+331
        lda bartab24,x
        sta SCREEN+371
        lda bartab25,x
        sta SCREEN+411
        lda bartab26,x
        sta SCREEN+451
        lda bartab27,x
        sta SCREEN+491
_skip5
        ldx barh+6
        cpx bard+6
        beq _skip6
        stx bard+6
        lda bartab0,x
        sta SCREEN+252
        lda bartab1,x
        sta SCREEN+292
        lda bartab2,x
        sta SCREEN+332
        lda bartab3,x
        sta SCREEN+372
        lda bartab4,x
        sta SCREEN+412
        lda bartab5,x
        sta SCREEN+452
        lda bartab6,x
        sta SCREEN+492
        lda bartab7,x
        sta SCREEN+253
        lda bartab8,x
        sta SCREEN+293
        lda bartab9,x
        sta SCREEN+333
        lda bartab10,x
        sta SCREEN+373
        lda bartab11,x
        sta SCREEN+413
        lda bartab12,x
        sta SCREEN+453
        lda bartab13,x
        sta SCREEN+493
_skip6
        rts
drawbars_b
        ldx barh+7
        cpx bard+7
        beq _skip7
        stx bard+7
        lda bartab14,x
        sta SCREEN+266
        lda bartab15,x
        sta SCREEN+306
        lda bartab16,x
        sta SCREEN+346
        lda bartab17,x
        sta SCREEN+386
        lda bartab18,x
        sta SCREEN+426
        lda bartab19,x
        sta SCREEN+466
        lda bartab20,x
        sta SCREEN+506
        lda bartab21,x
        sta SCREEN+267
        lda bartab22,x
        sta SCREEN+307
        lda bartab23,x
        sta SCREEN+347
        lda bartab24,x
        sta SCREEN+387
        lda bartab25,x
        sta SCREEN+427
        lda bartab26,x
        sta SCREEN+467
        lda bartab27,x
        sta SCREEN+507
_skip7
        ldx barh+8
        cpx bard+8
        beq _skip8
        stx bard+8
        lda bartab0,x
        sta SCREEN+268
        lda bartab1,x
        sta SCREEN+308
        lda bartab2,x
        sta SCREEN+348
        lda bartab3,x
        sta SCREEN+388
        lda bartab4,x
        sta SCREEN+428
        lda bartab5,x
        sta SCREEN+468
        lda bartab6,x
        sta SCREEN+508
        lda bartab7,x
        sta SCREEN+269
        lda bartab8,x
        sta SCREEN+309
        lda bartab9,x
        sta SCREEN+349
        lda bartab10,x
        sta SCREEN+389
        lda bartab11,x
        sta SCREEN+429
        lda bartab12,x
        sta SCREEN+469
        lda bartab13,x
        sta SCREEN+509
_skip8
        ldx barh+9
        cpx bard+9
        beq _skip9
        stx bard+9
        lda bartab14,x
        sta SCREEN+270
        lda bartab15,x
        sta SCREEN+310
        lda bartab16,x
        sta SCREEN+350
        lda bartab17,x
        sta SCREEN+390
        lda bartab18,x
        sta SCREEN+430
        lda bartab19,x
        sta SCREEN+470
        lda bartab20,x
        sta SCREEN+510
        lda bartab21,x
        sta SCREEN+271
        lda bartab22,x
        sta SCREEN+311
        lda bartab23,x
        sta SCREEN+351
        lda bartab24,x
        sta SCREEN+391
        lda bartab25,x
        sta SCREEN+431
        lda bartab26,x
        sta SCREEN+471
        lda bartab27,x
        sta SCREEN+511
_skip9
        ldx barh+10
        cpx bard+10
        beq _skip10
        stx bard+10
        lda bartab0,x
        sta SCREEN+272
        lda bartab1,x
        sta SCREEN+312
        lda bartab2,x
        sta SCREEN+352
        lda bartab3,x
        sta SCREEN+392
        lda bartab4,x
        sta SCREEN+432
        lda bartab5,x
        sta SCREEN+472
        lda bartab6,x
        sta SCREEN+512
        lda bartab7,x
        sta SCREEN+273
        lda bartab8,x
        sta SCREEN+313
        lda bartab9,x
        sta SCREEN+353
        lda bartab10,x
        sta SCREEN+393
        lda bartab11,x
        sta SCREEN+433
        lda bartab12,x
        sta SCREEN+473
        lda bartab13,x
        sta SCREEN+513
_skip10
        ldx barh+11
        cpx bard+11
        beq _skip11
        stx bard+11
        lda bartab14,x
        sta SCREEN+274
        lda bartab15,x
        sta SCREEN+314
        lda bartab16,x
        sta SCREEN+354
        lda bartab17,x
        sta SCREEN+394
        lda bartab18,x
        sta SCREEN+434
        lda bartab19,x
        sta SCREEN+474
        lda bartab20,x
        sta SCREEN+514
        lda bartab21,x
        sta SCREEN+275
        lda bartab22,x
        sta SCREEN+315
        lda bartab23,x
        sta SCREEN+355
        lda bartab24,x
        sta SCREEN+395
        lda bartab25,x
        sta SCREEN+435
        lda bartab26,x
        sta SCREEN+475
        lda bartab27,x
        sta SCREEN+515
_skip11
        ldx barh+12
        cpx bard+12
        beq _skip12
        stx bard+12
        lda bartab0,x
        sta SCREEN+276
        lda bartab1,x
        sta SCREEN+316
        lda bartab2,x
        sta SCREEN+356
        lda bartab3,x
        sta SCREEN+396
        lda bartab4,x
        sta SCREEN+436
        lda bartab5,x
        sta SCREEN+476
        lda bartab6,x
        sta SCREEN+516
        lda bartab7,x
        sta SCREEN+277
        lda bartab8,x
        sta SCREEN+317
        lda bartab9,x
        sta SCREEN+357
        lda bartab10,x
        sta SCREEN+397
        lda bartab11,x
        sta SCREEN+437
        lda bartab12,x
        sta SCREEN+477
        lda bartab13,x
        sta SCREEN+517
_skip12
        ldx barh+13
        cpx bard+13
        beq _skip13
        stx bard+13
        lda bartab14,x
        sta SCREEN+278
        lda bartab15,x
        sta SCREEN+318
        lda bartab16,x
        sta SCREEN+358
        lda bartab17,x
        sta SCREEN+398
        lda bartab18,x
        sta SCREEN+438
        lda bartab19,x
        sta SCREEN+478
        lda bartab20,x
        sta SCREEN+518
        lda bartab21,x
        sta SCREEN+279
        lda bartab22,x
        sta SCREEN+319
        lda bartab23,x
        sta SCREEN+359
        lda bartab24,x
        sta SCREEN+399
        lda bartab25,x
        sta SCREEN+439
        lda bartab26,x
        sta SCREEN+479
        lda bartab27,x
        sta SCREEN+519
_skip13
        rts
; --- raster kernel, generated by gfx.py: lines 51-192 ---
kernel_pre
        lda kd021+0
        ldx kd023+0
        rts
kernel
; line 51 (bad line)
        sta $d021
        stx $d023
        lda kd021+1
        ldx kd023+1
        nop
        nop
; line 52
        sta $d021
        stx $d023
        lda kd021+2
        ldx kd023+2
        bit $ea
        jsr wait16
; line 53
        sta $d021
        stx $d023
        lda kd021+3
        ldx kd023+3
        bit $ea
        jsr wait16
; line 54
        sta $d021
        stx $d023
        lda kd021+4
        ldx kd023+4
        bit $ea
        jsr wait16
; line 55
        sta $d021
        stx $d023
        lda kd021+5
        ldx kd023+5
        bit $ea
        jsr wait16
; line 56
        sta $d021
        stx $d023
        lda kd021+6
        ldx kd023+6
        bit $ea
        jsr wait16
; line 57
        sta $d021
        stx $d023
        lda kd021+7
        ldx kd023+7
        bit $ea
        jsr wait16
; line 58
        sta $d021
        stx $d023
        lda kd021+8
        ldx kd023+8
        bit $ea
        jsr wait16
; line 59 (bad line)
        sta $d021
        stx $d023
        lda kd021+9
        ldx kd023+9
        nop
        nop
; line 60
        sta $d021
        stx $d023
        lda kd021+10
        ldx kd023+10
        bit $ea
        jsr wait16
; line 61
        sta $d021
        stx $d023
        lda kd021+11
        ldx kd023+11
        bit $ea
        jsr wait16
; line 62
        sta $d021
        stx $d023
        lda kd021+12
        ldx kd023+12
        bit $ea
        jsr wait16
; line 63
        sta $d021
        stx $d023
        lda kd021+13
        ldx kd023+13
        bit $ea
        jsr wait16
; line 64
        sta $d021
        stx $d023
        lda kd021+14
        ldx kd023+14
        bit $ea
        jsr wait16
; line 65
        sta $d021
        stx $d023
        lda kd021+15
        ldx kd023+15
        bit $ea
        jsr wait16
; line 66
        sta $d021
        stx $d023
        lda kd021+16
        ldx kd023+16
        bit $ea
        jsr wait16
; line 67 (bad line)
        sta $d021
        stx $d023
        lda kd021+17
        ldx kd023+17
        nop
        nop
; line 68
        sta $d021
        stx $d023
        lda kd021+18
        ldx kd023+18
        bit $ea
        jsr wait16
; line 69
        sta $d021
        stx $d023
        lda kd021+19
        ldx kd023+19
        bit $ea
        jsr wait16
; line 70
        sta $d021
        stx $d023
        lda kd021+20
        ldx kd023+20
        bit $ea
        jsr wait16
; line 71
        sta $d021
        stx $d023
        lda kd021+21
        ldx kd023+21
        bit $ea
        jsr wait16
; line 72
        sta $d021
        stx $d023
        lda kd021+22
        ldx kd023+22
        bit $ea
        jsr wait16
; line 73
        sta $d021
        stx $d023
        lda kd021+23
        ldx kd023+23
        bit $ea
        jsr wait16
; line 74
        sta $d021
        stx $d023
        lda kd021+24
        ldx kd023+24
        bit $ea
        jsr wait16
; line 75 (bad line)
        sta $d021
        stx $d023
        lda kd021+25
        ldx kd023+25
        nop
        nop
; line 76
        sta $d021
        stx $d023
        lda kd021+26
        ldx kd023+26
        bit $ea
        jsr wait16
; line 77
        sta $d021
        stx $d023
        lda kd021+27
        ldx kd023+27
        bit $ea
        jsr wait16
; line 78
        sta $d021
        stx $d023
        lda kd021+28
        ldx kd023+28
        bit $ea
        jsr wait16
; line 79
        sta $d021
        stx $d023
        lda kd021+29
        ldx kd023+29
        bit $ea
        jsr wait16
; line 80
        sta $d021
        stx $d023
        lda kd021+30
        ldx kd023+30
        bit $ea
        jsr wait16
; line 81
        sta $d021
        stx $d023
        lda kd021+31
        ldx kd023+31
        bit $ea
        jsr wait16
; line 82
        sta $d021
        stx $d023
        lda kd021+32
        ldx kd023+32
        bit $ea
        jsr wait16
; line 83 (bad line)
        sta $d021
        stx $d023
        lda kd021+33
        ldx kd023+33
        nop
        nop
; line 84
        sta $d021
        stx $d023
        lda kd021+34
        ldx kd023+34
        bit $ea
        jsr wait16
; line 85
        sta $d021
        stx $d023
        lda kd021+35
        ldx kd023+35
        bit $ea
        jsr wait16
; line 86
        sta $d021
        stx $d023
        lda kd021+36
        ldx kd023+36
        bit $ea
        jsr wait16
; line 87
        sta $d021
        stx $d023
        lda kd021+37
        ldx kd023+37
        bit $ea
        jsr wait16
; line 88
        sta $d021
        stx $d023
        lda kd021+38
        ldx kd023+38
        bit $ea
        jsr wait16
; line 89
        sta $d021
        stx $d023
        lda kd021+39
        ldx kd023+39
        bit $ea
        jsr wait16
; line 90
        sta $d021
        stx $d023
        lda kd021+40
        ldx kd023+40
        bit $ea
        jsr wait16
; line 91 (bad line)
        sta $d021
        stx $d023
        lda kd021+41
        ldx kd023+41
        nop
        nop
; line 92
        sta $d021
        stx $d023
        lda kd021+42
        ldx kd023+42
        bit $ea
        jsr wait16
; line 93
        sta $d021
        stx $d023
        lda kd021+43
        ldx kd023+43
        bit $ea
        jsr wait16
; line 94
        sta $d021
        stx $d023
        lda kd021+44
        ldx kd023+44
        bit $ea
        jsr wait16
; line 95
        sta $d021
        stx $d023
        lda kd021+45
        ldx kd023+45
        bit $ea
        jsr wait16
; line 96
        sta $d021
        stx $d023
        lda kd021+46
        ldx kd023+46
        bit $ea
        jsr wait16
; line 97
        sta $d021
        stx $d023
        lda kd021+47
        ldx kd023+47
        bit $ea
        jsr wait16
; line 98
        sta $d021
        stx $d023
        lda kd021+48
        ldx kd023+48
        bit $ea
        jsr wait16
; line 99 (bad line)
        sta $d021
        stx $d023
        lda kd021+49
        ldx kd023+49
        ldy #$07
        nop
; line 100
        sta $d021
        stx $d023
        sty $d022
        lda kd021+50
        ldx kd023+50
        bit $ea
        jsr wait14
; line 101
        sta $d021
        stx $d023
        lda kd021+51
        ldx kd023+51
        bit $ea
        jsr wait16
; line 102
        sta $d021
        stx $d023
        lda kd021+52
        ldx kd023+52
        bit $ea
        jsr wait16
; line 103
        sta $d021
        stx $d023
        lda kd021+53
        ldx kd023+53
        bit $ea
        jsr wait16
; line 104
        sta $d021
        stx $d023
        lda kd021+54
        ldx kd023+54
        bit $ea
        jsr wait16
; line 105
        sta $d021
        stx $d023
        lda kd021+55
        ldx kd023+55
        bit $ea
        jsr wait16
; line 106
        sta $d021
        stx $d023
        lda kd021+56
        ldx kd023+56
        bit $ea
        jsr wait16
; line 107 (bad line)
        sta $d021
        stx $d023
        lda kd021+57
        ldx kd023+57
        nop
        nop
; line 108
        sta $d021
        stx $d023
        lda kd021+58
        ldx kd023+58
        bit $ea
        jsr wait16
; line 109
        sta $d021
        stx $d023
        lda kd021+59
        ldx kd023+59
        bit $ea
        jsr wait16
; line 110
        sta $d021
        stx $d023
        lda kd021+60
        ldx kd023+60
        bit $ea
        jsr wait16
; line 111
        sta $d021
        stx $d023
        lda kd021+61
        ldx kd023+61
        bit $ea
        jsr wait16
; line 112
        sta $d021
        stx $d023
        lda kd021+62
        ldx kd023+62
        bit $ea
        jsr wait16
; line 113
        sta $d021
        stx $d023
        lda kd021+63
        ldx kd023+63
        bit $ea
        jsr wait16
; line 114
        sta $d021
        stx $d023
        lda kd021+64
        ldx kd023+64
        bit $ea
        jsr wait16
; line 115 (bad line)
        sta $d021
        stx $d023
        lda kd021+65
        ldx kd023+65
        nop
        nop
; line 116
        sta $d021
        stx $d023
        lda kd021+66
        ldx kd023+66
        bit $ea
        jsr wait16
; line 117
        sta $d021
        stx $d023
        lda kd021+67
        ldx kd023+67
        bit $ea
        jsr wait16
; line 118
        sta $d021
        stx $d023
        lda kd021+68
        ldx kd023+68
        bit $ea
        jsr wait16
; line 119
        sta $d021
        stx $d023
        lda kd021+69
        ldx kd023+69
        bit $ea
        jsr wait16
; line 120
        sta $d021
        stx $d023
        lda kd021+70
        ldx kd023+70
        bit $ea
        jsr wait16
; line 121
        sta $d021
        stx $d023
        lda kd021+71
        ldx kd023+71
        bit $ea
        jsr wait16
; line 122
        sta $d021
        stx $d023
        lda kd021+72
        ldx kd023+72
        bit $ea
        jsr wait16
; line 123 (bad line)
        sta $d021
        stx $d023
        lda kd021+73
        ldx kd023+73
        nop
        nop
; line 124
        sta $d021
        stx $d023
        lda kd021+74
        ldx kd023+74
        bit $ea
        jsr wait16
; line 125
        sta $d021
        stx $d023
        lda kd021+75
        ldx kd023+75
        bit $ea
        jsr wait16
; line 126
        sta $d021
        stx $d023
        lda kd021+76
        ldx kd023+76
        bit $ea
        jsr wait16
; line 127
        sta $d021
        stx $d023
        lda kd021+77
        ldx kd023+77
        bit $ea
        jsr wait16
; line 128
        sta $d021
        stx $d023
        lda kd021+78
        ldx kd023+78
        bit $ea
        jsr wait16
; line 129
        sta $d021
        stx $d023
        lda kd021+79
        ldx kd023+79
        bit $ea
        jsr wait16
; line 130
        sta $d021
        stx $d023
        lda kd021+80
        ldx kd023+80
        bit $ea
        jsr wait16
; line 131 (bad line)
        sta $d021
        stx $d023
        lda kd021+81
        ldx kd023+81
        nop
        nop
; line 132
        sta $d021
        stx $d023
        lda kd021+82
        ldx kd023+82
        bit $ea
        jsr wait16
; line 133
        sta $d021
        stx $d023
        lda kd021+83
        ldx kd023+83
        bit $ea
        jsr wait16
; line 134
        sta $d021
        stx $d023
        lda kd021+84
        ldx kd023+84
        bit $ea
        jsr wait16
; line 135
        sta $d021
        stx $d023
        lda kd021+85
        ldx kd023+85
        bit $ea
        jsr wait16
; line 136
        sta $d021
        stx $d023
        lda kd021+86
        ldx kd023+86
        bit $ea
        jsr wait16
; line 137
        sta $d021
        stx $d023
        lda kd021+87
        ldx kd023+87
        bit $ea
        jsr wait16
; line 138
        sta $d021
        stx $d023
        lda kd021+88
        ldx kd023+88
        bit $ea
        jsr wait16
; line 139 (bad line)
        sta $d021
        stx $d023
        lda kd021+89
        ldx kd023+89
        nop
        nop
; line 140
        sta $d021
        stx $d023
        lda kd021+90
        ldx kd023+90
        bit $ea
        jsr wait16
; line 141
        sta $d021
        stx $d023
        lda kd021+91
        ldx kd023+91
        bit $ea
        jsr wait16
; line 142
        sta $d021
        stx $d023
        lda kd021+92
        ldx kd023+92
        bit $ea
        jsr wait16
; line 143
        sta $d021
        stx $d023
        lda kd021+93
        ldx kd023+93
        bit $ea
        jsr wait16
; line 144
        sta $d021
        stx $d023
        lda kd021+94
        ldx kd023+94
        bit $ea
        jsr wait16
; line 145
        sta $d021
        stx $d023
        lda kd021+95
        ldx kd023+95
        bit $ea
        jsr wait16
; line 146
        sta $d021
        stx $d023
        lda kd021+96
        ldx kd023+96
        bit $ea
        jsr wait16
; line 147 (bad line)
        sta $d021
        stx $d023
        lda kd021+97
        ldx kd023+97
        nop
        nop
; line 148
        sta $d021
        stx $d023
        lda kd021+98
        ldx kd023+98
        bit $ea
        jsr wait16
; line 149
        sta $d021
        stx $d023
        lda kd021+99
        ldx kd023+99
        bit $ea
        jsr wait16
; line 150
        sta $d021
        stx $d023
        lda kd021+100
        ldx kd023+100
        bit $ea
        jsr wait16
; line 151
        sta $d021
        stx $d023
        lda kd021+101
        ldx kd023+101
        bit $ea
        jsr wait16
; line 152
        sta $d021
        stx $d023
        lda kd021+102
        ldx kd023+102
        bit $ea
        jsr wait16
; line 153
        sta $d021
        stx $d023
        lda kd021+103
        ldx kd023+103
        bit $ea
        jsr wait16
; line 154
        sta $d021
        stx $d023
        lda kd021+104
        ldy #$08
        ldx #$04
        bit $ea
        jsr wait16
; line 155 (bad line)
        sta $d021
        sty $d016
        stx $d018
        lda kd021+105
        nop
        nop
; line 156
        sta $d021
        lda kd021+106
        bit $ea
        jsr wait20
; line 157
        sta $d021
        lda kd021+107
        bit $ea
        jsr wait20
; line 158
        sta $d021
        lda kd021+108
        bit $ea
        jsr wait20
; line 159
        sta $d021
        lda kd021+109
        bit $ea
        jsr wait20
; line 160
        sta $d021
        lda kd021+110
        bit $ea
        jsr wait20
; line 161
        sta $d021
        lda kd021+111
        bit $ea
        jsr wait20
; line 162
        sta $d021
        lda kd021+112
        bit $ea
        jsr wait20
; line 163 (bad line)
        sta $d021
        lda kd021+113
        nop
        nop
        nop
        nop
        nop
        nop
; line 164
        sta $d021
        lda kd021+114
        bit $ea
        jsr wait20
; line 165
        sta $d021
        lda kd021+115
        bit $ea
        jsr wait20
; line 166
        sta $d021
        lda kd021+116
        bit $ea
        jsr wait20
; line 167
        sta $d021
        lda kd021+117
        bit $ea
        jsr wait20
; line 168
        sta $d021
        lda kd021+118
        bit $ea
        jsr wait20
; line 169
        sta $d021
        lda kd021+119
        bit $ea
        jsr wait20
; line 170
        sta $d021
        lda kd021+120
        bit $ea
        jsr wait20
; line 171 (bad line)
        sta $d021
        lda kd021+121
        nop
        nop
        nop
        nop
        nop
        nop
; line 172
        sta $d021
        lda kd021+122
        bit $ea
        jsr wait20
; line 173
        sta $d021
        lda kd021+123
        bit $ea
        jsr wait20
; line 174
        sta $d021
        lda kd021+124
        bit $ea
        jsr wait20
; line 175
        sta $d021
        lda kd021+125
        bit $ea
        jsr wait20
; line 176
        sta $d021
        lda kd021+126
        bit $ea
        jsr wait20
; line 177
        sta $d021
        lda kd021+127
        bit $ea
        jsr wait20
; line 178
        sta $d021
        lda kd021+128
        bit $ea
        jsr wait20
; line 179 (bad line)
        sta $d021
        lda kd021+129
        nop
        nop
        nop
        nop
        nop
        nop
; line 180
        sta $d021
        lda kd021+130
        bit $ea
        jsr wait20
; line 181
        sta $d021
        lda kd021+131
        bit $ea
        jsr wait20
; line 182
        sta $d021
        lda kd021+132
        bit $ea
        jsr wait20
; line 183
        sta $d021
        lda kd021+133
        bit $ea
        jsr wait20
; line 184
        sta $d021
        lda kd021+134
        bit $ea
        jsr wait20
; line 185
        sta $d021
        lda kd021+135
        bit $ea
        jsr wait20
; line 186
        sta $d021
        lda kd021+136
        bit $ea
        jsr wait20
; line 187 (bad line)
        sta $d021
        lda kd021+137
        nop
        nop
        nop
        nop
        nop
        nop
; line 188
        sta $d021
        lda kd021+138
        bit $ea
        jsr wait20
; line 189
        sta $d021
        lda kd021+139
        bit $ea
        jsr wait20
; line 190
        sta $d021
        lda kd021+140
        bit $ea
        jsr wait20
; line 191
        sta $d021
        lda kd021+141
        bit $ea
        jsr wait20
; line 192
        sta $d021
        rts
; jsr waitK takes 12 + 2K cycles: K nops, then the rts
wait40  nop
wait39  nop
wait38  nop
wait37  nop
wait36  nop
wait35  nop
wait34  nop
wait33  nop
wait32  nop
wait31  nop
wait30  nop
wait29  nop
wait28  nop
wait27  nop
wait26  nop
wait25  nop
wait24  nop
wait23  nop
wait22  nop
wait21  nop
wait20  nop
wait19  nop
wait18  nop
wait17  nop
wait16  nop
wait15  nop
wait14  nop
wait13  nop
wait12  nop
wait11  nop
wait10  nop
wait9   nop
wait8   nop
wait7   nop
wait6   nop
wait5   nop
wait4   nop
wait3   nop
wait2   nop
wait1   nop
wait0   rts
