#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 SampoSoft - Francesco Sampoli
"""Writes src/ed25519_tab.asm (the curve constants), src/ed25519_pts.asm
(the comb of the ed25519 base point) and src/aes_tab.asm."""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "test"))
from ed25519_ref import B, D, L, P, SQRTM1, add, mul  # noqa: E402


def fe(n):
    b = (n % P).to_bytes(32, "little")
    return "\n".join("        .byte " + ", ".join(f"${x:02x}" for x in b[i:i + 16])
                     for i in (0, 16))


def main():
    out = ["; SPDX-License-Identifier: GPL-2.0-or-later",
           "; Copyright (C) 2026 SampoSoft - Francesco Sampoli",
           ";",
           "; Generated by gen_tables.py: do not edit.", ""]
    for name, value in (("ed_d", D), ("ed_d2", 2 * D), ("ed_sqrtm1", SQRTM1)):
        out += [name, fe(value)]
    lb = L.to_bytes(32, "little")
    out += ["ed_l", "        .byte " + ", ".join(f"${x:02x}" for x in lb[:16]),
            "        .byte " + ", ".join(f"${x:02x}" for x in lb[16:])]
    open(os.path.join(HERE, "src", "ed25519_tab.asm"), "w").write("\n".join(out) + "\n")
    out = ["; SPDX-License-Identifier: GPL-2.0-or-later",
           "; Copyright (C) 2026 SampoSoft - Francesco Sampoli",
           ";",
           "; Generated by gen_tables.py: do not edit. Points of the base; they",
           "; live in the RAM under the I/O (read through ed_load).", ""]
    out += ["; signed comb of B, 6 teeth 43 bits apart: entry j (0..31) is",
            "; P0 + e1 P1 + ... + e5 P5 with Pr = 2^(43 r) B, er = +1 if bit r-1 of",
            "; j is set, else -1; y+x, y-x, 2dxy (96 bytes each)", "ed_comb"]
    pr = [mul(1 << (43 * r), B) for r in range(6)]
    for j in range(32):
        p = pr[0]
        for r in range(1, 6):
            x, y = pr[r]
            p = add(p, (x, y) if j >> (r - 1) & 1 else ((P - x) % P, y))
        x, y = p
        out += [f"        ; entry {j}", fe(y + x), fe(y - x), fe(2 * D * x * y)]
    open(os.path.join(HERE, "src", "ed25519_pts.asm"), "w").write("\n".join(out) + "\n")
    aes()


def aes():
    """The AES S-box (FIPS 197, 5.1.1) and the GCM reduction table."""
    def gmul(a, b):
        r = 0
        while b:
            if b & 1:
                r ^= a
            a = (a << 1) ^ (0x11b if a & 0x80 else 0)
            b >>= 1
        return r
    inv = [0] + [next(y for y in range(1, 256) if gmul(x, y) == 1) for x in range(1, 256)]
    sbox = []
    for x in range(256):
        b = inv[x]
        s = b
        for k in range(1, 5):
            s ^= ((b << k) | (b >> (8 - k))) & 0xff
        sbox.append(s ^ 0x63)
    assert sbox[0] == 0x63 and sbox[0x53] == 0xed
    # GHASH: the byte o shifted out by x^8 comes back as o * x^128 reduced,
    # in the first two bytes (GCM bit order)
    r8 = []
    for o in range(256):
        v = 0
        for j in range(8):
            if o & (0x80 >> j):
                v ^= 0xe100 >> j
        r8.append(v)
    out = ["; SPDX-License-Identifier: GPL-2.0-or-later",
           "; Copyright (C) 2026 SampoSoft - Francesco Sampoli",
           ";",
           "; Generated by gen_tables.py: do not edit.", ""]

    def table(name, values):
        out.append(name)
        for i in range(0, 256, 16):
            out.append("        .byte " + ", ".join(f"${v:02x}" for v in values[i:i + 16]))
    table("aes_sbox", sbox)
    table("gcm_r8a", [v >> 8 for v in r8])
    table("gcm_r8b", [v & 0xff for v in r8])
    open(os.path.join(HERE, "src", "aes_tab.asm"), "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
