; SPDX-License-Identifier: GPL-2.0-or-later
; Copyright (C) 2026 SampoSoft - Francesco Sampoli
;
; Generated by gen_tables.py: do not edit.

ed_d
        .byte $a3, $78, $59, $13, $ca, $4d, $eb, $75, $ab, $d8, $41, $41, $4d, $0a, $70, $00
        .byte $98, $e8, $79, $77, $79, $40, $c7, $8c, $73, $fe, $6f, $2b, $ee, $6c, $03, $52
ed_d2
        .byte $59, $f1, $b2, $26, $94, $9b, $d6, $eb, $56, $b1, $83, $82, $9a, $14, $e0, $00
        .byte $30, $d1, $f3, $ee, $f2, $80, $8e, $19, $e7, $fc, $df, $56, $dc, $d9, $06, $24
ed_sqrtm1
        .byte $b0, $a0, $0e, $4a, $27, $1b, $ee, $c4, $78, $e4, $2f, $ad, $06, $18, $43, $2f
        .byte $a7, $d7, $fb, $3d, $99, $00, $4d, $2b, $0b, $df, $c1, $4f, $80, $24, $83, $2b
ed_l
        .byte $ed, $d3, $f5, $5c, $1a, $63, $12, $58, $d6, $9c, $f7, $a2, $de, $f9, $de, $14
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $10
