// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 SampoSoft - Francesco Sampoli
// Behaviour modelled on VICE 3.10 (c64/cart/*.c); see CREDITS.md.

//! Cartridges: CRT file parsing and banking of the supported types.
//!
//! The C64 sees a cartridge through the /EXROM and /GAME lines, which the PLA
//! combines with LORAM/HIRAM/CHAREN (see `Bus::map_read`), and through the
//! two I/O areas $DE00-$DEFF (I/O1) and $DF00-$DFFF (I/O2), where the
//! banking registers live:
//!
//! | /EXROM | /GAME | mode    | visible ROMs                                   |
//! |--------|-------|---------|------------------------------------------------|
//! | high   | high  | off     | none                                           |
//! | low    | high  | 8K      | ROML at $8000-$9FFF                            |
//! | low    | low   | 16K     | ROML at $8000, ROMH at $A000-$BFFF             |
//! | high   | low   | Ultimax | ROML at $8000, ROMH at $E000-$FFFF, only 4K of RAM |
//!
//! ROMs are kept in 8K banks, ROML and ROMH separately; a missing bank reads
//! $FF (erased flash or missing EPROM). A chip smaller than 8K repeats
//! within its window, as on the bus (high address lines not connected).
//!
//! EasyFlash, GMod2 and Megabyter have writable flash (see `flash.rs`): the
//! commands arrive with CPU writes in Ultimax mode, at $8000-$9FFF for the
//! ROML chip and at $E000-$FFFF for the ROMH one (the GMod2 enables Ultimax
//! only on writes and programs through the high window).
//!
//! The behaviour of each type follows the CRT documentation and VICE, which
//! it is compared against by the tests in tests/vice_mem.rs (test cartridges
//! generated by tools/vice_tests.py).

mod eeprom;
mod flash;

use eeprom::M93c86;
use flash::{Chip, Flash};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    Off,
    Game8K,
    Game16K,
    Ultimax,
}

impl Mode {
    /// From the /EXROM and /GAME lines (true = low, active).
    fn from_lines(exrom_low: bool, game_low: bool) -> Self {
        match (exrom_low, game_low) {
            (false, false) => Mode::Off,
            (true, false) => Mode::Game8K,
            (true, true) => Mode::Game16K,
            (false, true) => Mode::Ultimax,
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Mode::Off => "off",
            Mode::Game8K => "8K",
            Mode::Game16K => "16K",
            Mode::Ultimax => "Ultimax",
        }
    }
}

/// Supported cartridge types, with their CRT format number.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Kind {
    /// 0: fixed ROMs, 8K, 16K or Ultimax according to the lines in the header.
    Normal,
    /// 5: 8K banks selected with $DE00 (bits 0-5). Up to 256K in 16K mode
    /// with the same bank also at $A000; the 512K one (Terminator 2) in 8K mode.
    Ocean,
    /// 7: Fun Play / Power Play: 16 banks, $DE00 = bank bits 5-3 and 0;
    /// $86 disables the ROM.
    FunPlay,
    /// 8: 4 16K banks; $DF00: bits 0-1 bank, bit 2 disables, bit 3 locks
    /// the register until reset.
    SuperGames,
    /// 15: C64 Game System / System 3: 64 banks, any access to
    /// $DE00-$DEFF selects the bank with the low 6 bits of the address.
    Gs,
    /// 17: 16 banks, selected by reading $DE00-$DE0F.
    Dinamic,
    /// 18: Zaxxon / Super Zaxxon: 4K at $8000 mirrored at $9000; a read at
    /// $8000-$8FFF maps bank 0 at $A000, at $9000-$9FFF bank 1.
    Zaxxon,
    /// 19: Magic Desk / Domark / HES Australia: $DE00 bits 0-6 bank, bit 7
    /// disables the ROM.
    MagicDesk,
    /// 23: 16K or 32K in 16K mode; reading $DE00 switches to bank 1, reading
    /// $DF00 disables the cartridge.
    Ross,
    /// 32: EasyFlash: $DE00 bank (0-63), $DE02 mode, 256 bytes of RAM at $DF00.
    EasyFlash,
    /// 57: RGCD (and Hucky, revision 1 with banks in reverse order):
    /// $DE00 bits 0-2 bank, bit 3 disables until reset.
    Rgcd,
    /// 60: GMod2: 512K flash, $DE00 bits 0-5 bank, bit 6 disables the ROM and
    /// selects the serial EEPROM (bit 5 clock, bit 4 data), read at bit 7.
    GMod2,
    /// 74: Drean (Argentinian H.E.R.O.): $DF00 bits 0-1 bank, bit 5 disables.
    Drean,
    /// 85: Magic Desk 16K: like Magic Desk but with 16K banks.
    MagicDesk16,
    /// 86: Megabyter: 1M flash, $DE00 bank (0-127), $DE02 mode.
    Megabyter,
    /// 87: Magic Desk Plus: Magic Desk with 128K SRAM and/or parallel EEPROM
    /// in a 256-byte window at $DF00 ($DE01 page, $DE03 control).
    MagicDeskPlus,
}

impl Kind {
    fn from_crt(t: u16) -> Option<Kind> {
        Some(match t {
            0 => Kind::Normal,
            5 => Kind::Ocean,
            7 => Kind::FunPlay,
            8 => Kind::SuperGames,
            15 => Kind::Gs,
            17 => Kind::Dinamic,
            18 => Kind::Zaxxon,
            19 => Kind::MagicDesk,
            23 => Kind::Ross,
            32 => Kind::EasyFlash,
            57 => Kind::Rgcd,
            60 => Kind::GMod2,
            74 => Kind::Drean,
            85 => Kind::MagicDesk16,
            86 => Kind::Megabyter,
            87 => Kind::MagicDeskPlus,
            _ => return None,
        })
    }

    pub fn crt_type(self) -> u16 {
        match self {
            Kind::Normal => 0,
            Kind::Ocean => 5,
            Kind::FunPlay => 7,
            Kind::SuperGames => 8,
            Kind::Gs => 15,
            Kind::Dinamic => 17,
            Kind::Zaxxon => 18,
            Kind::MagicDesk => 19,
            Kind::Ross => 23,
            Kind::EasyFlash => 32,
            Kind::Rgcd => 57,
            Kind::GMod2 => 60,
            Kind::Drean => 74,
            Kind::MagicDesk16 => 85,
            Kind::Megabyter => 86,
            Kind::MagicDeskPlus => 87,
        }
    }

    pub fn name(self) -> &'static str {
        crt_type_name(self.crt_type())
    }

    /// Types with flash: all banks exist, those missing from the CRT are
    /// erased ($FF) and the register does not wrap around the present banks.
    fn flash(self) -> bool {
        matches!(self, Kind::EasyFlash | Kind::GMod2 | Kind::Megabyter)
    }

    /// Types in which every chip goes into the ROML banks by its bank
    /// number, whatever the load address in the CRT.
    fn roml_only(self) -> bool {
        matches!(self, Kind::Ocean | Kind::FunPlay | Kind::Gs | Kind::Dinamic | Kind::MagicDesk
            | Kind::Rgcd | Kind::GMod2 | Kind::Drean | Kind::Megabyter | Kind::MagicDeskPlus)
    }

    /// Bank bits of the register.
    fn register_mask(self) -> u8 {
        match self {
            Kind::Normal => 0,
            Kind::SuperGames | Kind::Drean => 0x03,
            Kind::Rgcd => 0x07,
            Kind::FunPlay | Kind::Dinamic => 0x0F,
            Kind::Zaxxon | Kind::Ross => 0x01,
            Kind::Ocean | Kind::Gs | Kind::EasyFlash | Kind::GMod2 => 0x3F,
            Kind::MagicDesk | Kind::MagicDesk16 | Kind::Megabyter | Kind::MagicDeskPlus => 0x7F,
        }
    }
}

/// Names of the CRT format types (unsupported ones too, for messages).
pub fn crt_type_name(t: u16) -> &'static str {
    const NAMES: [&str; 88] = [
        "Normal", "Action Replay", "KCS Power Cartridge", "Final Cartridge III",
        "Simons' BASIC", "Ocean", "Expert Cartridge", "Fun Play / Power Play",
        "Super Games", "Atomic Power", "Epyx Fastload", "Westermann Learning",
        "Rex Utility", "Final Cartridge I", "Magic Formel", "C64 Game System / System 3",
        "Warp Speed", "Dinamic", "Zaxxon / Super Zaxxon", "Magic Desk / Domark / HES Australia",
        "Super Snapshot V5", "Comal-80", "Structured BASIC", "Ross",
        "Dela EP64", "Dela EP7x8", "Dela EP256", "Rex EP256",
        "Mikro Assembler", "Final Cartridge Plus", "Action Replay 4", "Stardos",
        "EasyFlash", "EasyFlash Xbank", "Capture", "Action Replay 3",
        "Retro Replay", "MMC64", "MMC Replay", "IDE64",
        "Super Snapshot V4", "IEEE-488 Interface", "Game Killer", "Prophet64",
        "EXOS", "Freeze Frame", "Freeze Machine", "Snapshot64",
        "Super Explode V5.0", "Magic Voice", "Action Replay 2", "MACH 5",
        "Diashow-Maker", "Pagefox", "Kingsoft", "Silverrock 128K",
        "Formel 64", "RGCD", "RR-Net MK3", "EasyCalc",
        "GMod2", "MAX Basic", "GMod3", "ZIPP-CODE 48",
        "Blackbox V8", "Blackbox V3", "Blackbox V4", "REX RAM-Floppy",
        "BIS-Plus", "SD-BOX", "MultiMAX", "Blackbox V9",
        "Lt. Kernal Host Adaptor", "RAMLink", "Drean", "IEEE Flash! 64",
        "Turtle Graphics II", "Freeze Frame MK2", "Partner 64", "Hyper-BASIC MK2",
        "Universal Cartridge 1", "Universal Cartridge 1.5", "Universal Cartridge 2", "BMP Data Turbo 2000",
        "Profi-DOS", "Magic Desk 16", "Megabyter", "Magic Desk Plus",
    ];
    NAMES.get(t as usize).copied().unwrap_or("unknown")
}

/// EasyFlash: mode from register $DE02 (bit 0 GAME, bit 1 EXROM, bit 2 M).
/// With M=1 /GAME follows bit G; with M=0 it is set by the "boot" jumper,
/// which is closed on game cartridges (/GAME low: it starts in Ultimax with
/// the reset vector from bank 0's ROMH). `$87` is 16K with LED, `$04`
/// disables the cartridge (EasyLoader writes it before starting a program).
const EASYFLASH_MODES: [Mode; 8] = [
    Mode::Ultimax, Mode::Ultimax, Mode::Game16K, Mode::Game16K,
    Mode::Off, Mode::Ultimax, Mode::Game8K, Mode::Game16K,
];

const BANK: usize = 0x2000;

/// Magic Desk Plus: 128K SRAM (two halves selected by bit 0 of $DE03).
const MDP_SRAM: usize = 0x20000;

pub struct CartState {
    pub kind: Kind,
    pub name: String,
    /// Hardware revision from the CRT header ($1A).
    pub revision: u8,
    /// 8K ROML (at $8000) and ROMH (at $A000 or $E000) banks, back to back.
    roml: Vec<u8>,
    romh: Vec<u8>,
    pub roml_bank: u8,
    pub romh_bank: u8,
    pub mode: Mode,
    /// Mode after reset (Normal: the lines in the CRT header).
    boot_mode: Mode,
    /// Last value written to registers $DE00-$DE03 (or $DF00 for types
    /// with the register in I/O2, in `regs[0]`).
    pub regs: [u8; 4],
    bank_mask: u8,
    /// Super Games: register locked; RGCD: cartridge disabled until reset.
    locked: bool,
    /// EasyFlash: 256 bytes at $DF00; Magic Desk Plus: 128K SRAM.
    ram: Vec<u8>,
    /// GMod2: serial EEPROM.
    eeprom: Option<M93c86>,
    /// Flash chip commands on ROML and ROMH (the data is in `roml` and `romh`).
    flash_lo: Option<Flash>,
    flash_hi: Option<Flash>,
    /// Magic Desk Plus: parallel EEPROM (8K or 32K).
    nv: Vec<u8>,
    nv_dirty: bool,
    /// File where EEPROM and non-volatile memory are kept between sessions.
    pub nvram_path: String,
}

impl Default for CartState {
    fn default() -> Self {
        Self::new(Kind::Normal, Mode::Off)
    }
}

impl CartState {
    fn new(kind: Kind, boot_mode: Mode) -> Self {
        Self {
            kind,
            name: String::new(),
            revision: 0,
            roml: Vec::new(),
            romh: Vec::new(),
            roml_bank: 0,
            romh_bank: 0,
            mode: boot_mode,
            boot_mode,
            regs: [0; 4],
            bank_mask: 0,
            locked: false,
            ram: Vec::new(),
            eeprom: None,
            flash_lo: None,
            flash_hi: None,
            nv: Vec::new(),
            nv_dirty: false,
            nvram_path: String::new(),
        }
    }

    /// Hardware reset: the cartridge registers go back to zero (bank 0,
    /// boot mode). RAM and EEPROM keep their contents.
    pub fn reset(&mut self) {
        self.mode = self.boot_mode;
        self.roml_bank = 0;
        self.romh_bank = 0;
        self.regs = [0; 4];
        self.locked = false;
        for f in [&mut self.flash_lo, &mut self.flash_hi].into_iter().flatten() {
            f.reset();
        }
        // Cleared registers are equivalent to writing 0 (on the Hucky, for
        // example, a register at 0 selects the last bank)
        match self.kind {
            Kind::Ocean | Kind::FunPlay | Kind::MagicDesk | Kind::MagicDesk16 | Kind::Rgcd
            | Kind::GMod2 => self.write_io1(0, 0),
            Kind::EasyFlash | Kind::Megabyter => {
                self.write_io1(0, 0);
                self.write_io1(2, 0);
            }
            Kind::MagicDeskPlus => {
                for off in 0..4 {
                    self.write_io1(off, 0);
                }
            }
            Kind::SuperGames | Kind::Drean => self.write_io2(0, 0),
            Kind::Normal | Kind::Gs | Kind::Dinamic | Kind::Zaxxon | Kind::Ross => {}
        }
    }

    pub fn ultimax(&self) -> bool {
        self.mode == Mode::Ultimax
    }

    // ── ROM ───────────────────────────────────────────────────────────────────

    fn byte(rom: &[u8], bank: u8, off: u16) -> u8 {
        rom.get((bank as usize) * BANK + (off as usize & (BANK - 1))).copied().unwrap_or(0xFF)
    }

    /// CPU read from ROML ($8000-$9FFF, offset 0-$1FFF) at cycle `now`.
    #[inline]
    pub fn read_roml(&mut self, off: u16, now: u64) -> u8 {
        if self.kind == Kind::Zaxxon {
            self.romh_bank = (off >> 12) as u8 & 1;
        }
        match &mut self.flash_lo {
            Some(f) => f.read(&mut self.roml, Self::offset(self.roml_bank, off), now),
            None => self.peek_roml(off),
        }
    }

    pub fn peek_roml(&self, off: u16) -> u8 {
        Self::byte(&self.roml, self.roml_bank, off)
    }

    /// CPU read from ROMH ($A000-$BFFF in 16K, $E000-$FFFF in Ultimax,
    /// offset 0-$1FFF).
    #[inline]
    pub fn read_romh(&mut self, off: u16, now: u64) -> u8 {
        match &mut self.flash_hi {
            Some(f) => f.read(&mut self.romh, Self::offset(self.romh_bank, off), now),
            None => self.peek_romh(off),
        }
    }

    pub fn peek_romh(&self, off: u16) -> u8 {
        match self.kind {
            // The same 8K bank on ROML and ROMH
            Kind::Ocean => Self::byte(&self.roml, self.roml_bank, off),
            _ => Self::byte(&self.romh, self.romh_bank, off),
        }
    }

    fn offset(bank: u8, off: u16) -> usize {
        (bank as usize) * BANK + (off as usize & (BANK - 1))
    }

    /// CPU write to $8000-$9FFF in Ultimax: commands to the ROML flash.
    pub fn write_roml(&mut self, off: u16, v: u8, now: u64) {
        if let Some(f) = &mut self.flash_lo {
            f.write(&mut self.roml, Self::offset(self.roml_bank, off), v, now);
        }
    }

    /// CPU write to $E000-$FFFF in Ultimax: commands to the ROMH flash; the
    /// GMod2 has a single chip and programs it from here.
    pub fn write_romh(&mut self, off: u16, v: u8, now: u64) {
        if self.kind == Kind::GMod2 {
            self.write_roml(off, v, now);
        } else if let Some(f) = &mut self.flash_hi {
            f.write(&mut self.romh, Self::offset(self.romh_bank, off), v, now);
        }
    }

    /// GMod2 with $DE00 bits 7 and 6: /GAME low only on write cycles
    /// (Ultimax for writes, cartridge disabled for reads).
    pub fn ultimax_writes(&self) -> bool {
        self.kind == Kind::GMod2 && self.regs[0] & 0xC0 == 0xC0
    }

    // ── I/O1 ($DE00-$DEFF) ────────────────────────────────────────────────────

    /// Write to I/O1 (`off` = low byte of the address).
    pub fn write_io1(&mut self, off: u8, v: u8) {
        match self.kind {
            Kind::Ocean => {
                self.regs[0] = v;
                self.roml_bank = v & self.bank_mask;
            }
            Kind::FunPlay => {
                self.regs[0] = v;
                self.roml_bank = ((v >> 3) & 7) | ((v & 1) << 3);
                match v & 0xC6 {
                    0x00 => self.mode = Mode::Game8K,
                    0x86 => self.mode = Mode::Off,
                    _ => {} // values never used by software: mode unchanged
                }
            }
            Kind::Gs => {
                self.regs[0] = v;
                self.roml_bank = off & self.bank_mask;
            }
            Kind::MagicDesk => self.magic_desk(v, Mode::Game8K),
            Kind::MagicDesk16 => self.magic_desk(v, Mode::Game16K),
            Kind::MagicDeskPlus => match off & 3 {
                0 => self.magic_desk(v, Mode::Game8K),
                1 => self.regs[1] = v,
                3 => self.regs[3] = v,
                _ => {}
            },
            Kind::EasyFlash => {
                if off & 2 == 0 {
                    self.regs[0] = v & 0x3F;
                    self.roml_bank = v & 0x3F;
                    self.romh_bank = v & 0x3F;
                } else {
                    self.regs[2] = v & 0x87;
                    self.mode = EASYFLASH_MODES[(v & 7) as usize];
                }
            }
            Kind::Rgcd => {
                self.regs[0] = v & 0x0F;
                // Hucky: banks in reverse order
                let v = if self.revision == 1 { v ^ 7 } else { v };
                self.locked |= v & 0x08 != 0;
                if self.locked {
                    self.mode = Mode::Off;
                } else {
                    self.roml_bank = v & self.bank_mask;
                    self.mode = Mode::Game8K;
                }
            }
            Kind::GMod2 => {
                self.regs[0] = v;
                self.roml_bank = v & 0x3F;
                // Bit 6: ROM disabled (with bit 7, Ultimax on writes only
                // to program the flash, see `ultimax_writes`)
                self.mode = if v & 0x40 != 0 { Mode::Off } else { Mode::Game8K };
                if let Some(e) = &mut self.eeprom {
                    e.set_lines(v & 0x40 != 0, v & 0x20 != 0, v & 0x10 != 0);
                }
            }
            Kind::Megabyter => {
                // Only A1 is decoded
                if off & 2 == 0 {
                    self.regs[0] = v & 0x7F;
                    self.roml_bank = v & 0x7F;
                } else {
                    self.regs[2] = v & 0x83;
                    self.mode = [Mode::Game8K, Mode::Game16K, Mode::Off, Mode::Ultimax][(v & 3) as usize];
                }
            }
            Kind::Normal | Kind::SuperGames | Kind::Dinamic | Kind::Zaxxon | Kind::Ross
            | Kind::Drean => {}
        }
    }

    fn magic_desk(&mut self, v: u8, on: Mode) {
        self.regs[0] = v & (0x80 | self.bank_mask);
        self.roml_bank = v & self.bank_mask;
        self.romh_bank = v & self.bank_mask;
        self.mode = if v & 0x80 != 0 { Mode::Off } else { on };
    }

    /// CPU read from I/O1: `None` if the cartridge does not respond (open
    /// bus). `open` is the byte on the open bus, for the bits the cartridge
    /// does not drive (GMod2: bits 0-6).
    pub fn read_io1(&mut self, off: u8, open: u8) -> Option<u8> {
        match self.kind {
            Kind::Gs => self.roml_bank = off & self.bank_mask,
            Kind::Dinamic if off < 16 => self.roml_bank = off,
            Kind::Ross if self.bank_mask > 0 => {
                self.roml_bank = 1;
                self.romh_bank = 1;
            }
            Kind::GMod2 => {
                let e = self.eeprom.as_mut()?;
                return (self.regs[0] & 0x40 != 0).then(|| (e.read_do() as u8) << 7 | open & 0x7F);
            }
            _ => {}
        }
        None
    }

    /// I/O1 read without side effects (debugger).
    pub fn peek_io1(&self, _off: u8, open: u8) -> Option<u8> {
        match self.kind {
            Kind::GMod2 => {
                let e = self.eeprom.as_ref()?;
                (self.regs[0] & 0x40 != 0).then(|| (e.peek_do() as u8) << 7 | open & 0x7F)
            }
            _ => None,
        }
    }

    // ── I/O2 ($DF00-$DFFF) ────────────────────────────────────────────────────

    pub fn write_io2(&mut self, off: u8, v: u8) {
        match self.kind {
            Kind::EasyFlash => self.ram[off as usize] = v,
            Kind::SuperGames if !self.locked => {
                self.regs[0] = v;
                self.roml_bank = v & 3;
                self.romh_bank = v & 3;
                self.mode = if v & 4 != 0 { Mode::Off } else { Mode::Game16K };
                self.locked = v & 8 != 0;
            }
            Kind::Drean => {
                self.regs[0] = v & 0x23;
                self.roml_bank = v & 3;
                self.mode = if v & 0x20 != 0 { Mode::Off } else { Mode::Game8K };
            }
            Kind::MagicDeskPlus => {
                if let Some(i) = self.mdp_index(off) {
                    match i {
                        MdpMem::Sram(i) => self.ram[i] = v,
                        MdpMem::Eeprom(i) => {
                            self.nv[i] = v;
                            self.nv_dirty = true;
                        }
                    }
                }
            }
            _ => {}
        }
    }

    pub fn read_io2(&mut self, off: u8) -> Option<u8> {
        if self.kind == Kind::Ross {
            self.mode = Mode::Off;
            return None;
        }
        self.peek_io2(off)
    }

    pub fn peek_io2(&self, off: u8) -> Option<u8> {
        match self.kind {
            Kind::EasyFlash => Some(self.ram[off as usize]),
            Kind::MagicDeskPlus => self.mdp_index(off).map(|m| match m {
                MdpMem::Sram(i) => self.ram[i],
                MdpMem::Eeprom(i) => self.nv[i],
            }),
            _ => None,
        }
    }

    /// Magic Desk Plus: cell seen at $DF00+off. $DE03 bit 5 selects the SRAM
    /// (bit 0 the 64K half) or the EEPROM; $DE01 is the 256-byte page.
    fn mdp_index(&self, off: u8) -> Option<MdpMem> {
        let page = self.regs[1] as usize;
        let ctrl = self.regs[3];
        if ctrl & 0x20 != 0 {
            (!self.ram.is_empty()).then(|| MdpMem::Sram((ctrl as usize & 1) << 16 | page << 8 | off as usize))
        } else {
            let pages = self.nv.len() >> 8;
            (pages > 0).then(|| MdpMem::Eeprom((page & (pages - 1)) << 8 | off as usize))
        }
    }

    // ── Non-volatile memory ───────────────────────────────────────────────────

    /// True if the cartridge has memory to keep between sessions.
    pub fn has_nvram(&self) -> bool {
        self.eeprom.is_some() || !self.nv.is_empty() || self.flash_lo.is_some()
    }

    /// Non-volatile memory, back to back: serial EEPROM, ROML flash, ROMH
    /// flash, parallel EEPROM.
    pub fn nvram(&self) -> Vec<u8> {
        let mut out = Vec::new();
        if let Some(e) = &self.eeprom {
            out.extend_from_slice(&e.data[..]);
        }
        if self.flash_lo.is_some() {
            out.extend_from_slice(&self.roml);
        }
        if self.flash_hi.is_some() {
            out.extend_from_slice(&self.romh);
        }
        out.extend_from_slice(&self.nv);
        out
    }

    pub fn nvram_dirty(&self) -> bool {
        self.nv_dirty
            || self.eeprom.as_ref().is_some_and(|e| e.dirty)
            || [&self.flash_lo, &self.flash_hi].into_iter().flatten().any(|f| f.dirty)
    }

    pub fn clear_nvram_dirty(&mut self) {
        self.nv_dirty = false;
        if let Some(e) = &mut self.eeprom {
            e.dirty = false;
        }
        for f in [&mut self.flash_lo, &mut self.flash_hi].into_iter().flatten() {
            f.dirty = false;
        }
    }

    /// Reloads the memory saved by `nvram` (same layout and size, otherwise
    /// an error and no change).
    pub fn load_nvram(&mut self, data: &[u8]) -> Result<(), String> {
        let expected = self.nvram().len();
        if data.len() != expected {
            return Err(format!("{} bytes instead of {expected}", data.len()));
        }
        let mut rest = data;
        let mut take = |dest: &mut [u8]| {
            let (a, b) = rest.split_at(dest.len());
            dest.copy_from_slice(a);
            rest = b;
        };
        if let Some(e) = &mut self.eeprom {
            take(&mut e.data[..]);
        }
        if self.flash_lo.is_some() {
            take(&mut self.roml);
        }
        if self.flash_hi.is_some() {
            take(&mut self.romh);
        }
        take(&mut self.nv);
        Ok(())
    }
}

enum MdpMem {
    Sram(usize),
    Eeprom(usize),
}

// ── CRT ───────────────────────────────────────────────────────────────────────

struct CrtChip<'a> {
    bank: usize,
    load: u16,
    data: &'a [u8],
}

/// Copies `data` into bank `bank` starting at `off`, extending the ROM with
/// empty ($FF) banks.
fn put(rom: &mut Vec<u8>, bank: usize, off: usize, data: &[u8]) {
    if rom.len() < (bank + 1) * BANK {
        rom.resize((bank + 1) * BANK, 0xFF);
    }
    let n = data.len().min(BANK - off);
    rom[bank * BANK + off..bank * BANK + off + n].copy_from_slice(&data[..n]);
}

/// A chip smaller than 8K, alone in its window, repeats until it fills it:
/// on the bus the high address lines are not connected.
fn mirror(rom: &mut [u8], bank: usize, off: usize, len: usize) {
    if len == 0 || len >= BANK || BANK % len != 0 {
        return;
    }
    let window = &mut rom[bank * BANK..(bank + 1) * BANK];
    let start = off - off % len;
    let chip = window[start..start + len].to_vec();
    for chunk in window.chunks_mut(len) {
        chunk.copy_from_slice(&chip);
    }
}

/// Parses a .crt file.
pub fn parse_crt(data: &[u8]) -> Result<CartState, String> {
    if data.len() < 0x40 || &data[0..16] != b"C64 CARTRIDGE   " {
        return Err("not a CRT file".into());
    }
    let be16 = |i: usize| u16::from_be_bytes([data[i], data[i + 1]]);
    let be32 = |i: usize| u32::from_be_bytes(data[i..i + 4].try_into().unwrap()) as usize;
    // Some CRTs declare $20: the header is $40 bytes anyway
    let header_len = be32(0x10).max(0x40);
    let crt_type = be16(0x16);
    // Lines in the header: 0 = low (active)
    let exrom_low = data[0x18] == 0;
    let game_low = data[0x19] == 0;
    let revision = data[0x1A];
    let name_raw = &data[0x20..0x40];
    let name_end = name_raw.iter().position(|&b| b == 0).unwrap_or(32);
    let name = String::from_utf8_lossy(&name_raw[..name_end]).trim_end().to_string();

    let kind = Kind::from_crt(crt_type).ok_or_else(|| {
        format!("unsupported cartridge type {crt_type} ({})", crt_type_name(crt_type))
    })?;

    let mut chips = Vec::new();
    let mut pos = header_len;
    while pos + 16 <= data.len() && &data[pos..pos + 4] == b"CHIP" {
        let packet_len = be32(pos + 4);
        let bank = be16(pos + 10) as usize;
        let load = be16(pos + 12);
        let size = be16(pos + 14) as usize;
        let start = pos + 16;
        if size == 0 || start + size > data.len() {
            return Err(format!("CHIP packet {} truncated", chips.len()));
        }
        chips.push(CrtChip { bank, load, data: &data[start..start + size] });
        if packet_len < 16 {
            return Err(format!("CHIP packet {} with invalid length", chips.len()));
        }
        pos += packet_len;
    }
    if chips.is_empty() {
        return Err("no CHIP packets".into());
    }

    let boot_mode = match kind {
        Kind::Normal => Mode::from_lines(exrom_low, game_low),
        // 512K Ocean: 8K mode, the others 16K
        Kind::Ocean => {
            if chips.iter().any(|c| c.bank >= 32) { Mode::Game8K } else { Mode::Game16K }
        }
        Kind::SuperGames | Kind::Zaxxon | Kind::Ross | Kind::MagicDesk16 => Mode::Game16K,
        Kind::EasyFlash => EASYFLASH_MODES[0],
        _ => Mode::Game8K,
    };
    let mut cart = CartState::new(kind, boot_mode);
    cart.name = name;
    cart.revision = revision;

    let mut highest = 0;
    // (ROMH?, bank, offset, length) of every placed chip
    let mut placed: Vec<(bool, usize, usize, usize)> = Vec::new();
    for chip in &chips {
        let bank = match kind {
            // In the CRT the bank is written as the register value
            Kind::FunPlay => ((chip.bank >> 3) & 7) | ((chip.bank & 1) << 3),
            _ => chip.bank,
        };
        if bank > kind.register_mask() as usize {
            return Err(format!("bank {bank} out of range for type {}", kind.name()));
        }
        highest = highest.max(bank);
        if kind.roml_only() {
            if chip.data.len() > BANK {
                return Err(format!("{}-byte chip, this type uses 8K banks", chip.data.len()));
            }
            put(&mut cart.roml, bank, 0, chip.data);
            placed.push((false, bank, 0, chip.data.len()));
            continue;
        }
        match chip.load {
            0x8000..=0x9FFF => {
                let off = (chip.load - 0x8000) as usize;
                let (lo, hi) = chip.data.split_at(chip.data.len().min(BANK - off));
                put(&mut cart.roml, bank, off, lo);
                placed.push((false, bank, off, lo.len()));
                // 16K chip: the second half is ROMH
                if !hi.is_empty() {
                    let hi = &hi[..hi.len().min(BANK)];
                    put(&mut cart.romh, bank, 0, hi);
                    placed.push((true, bank, 0, hi.len()));
                }
            }
            0xA000..=0xBFFF | 0xE000..=0xFFFF => {
                let off = (chip.load & 0x1FFF) as usize;
                put(&mut cart.romh, bank, off, chip.data);
                placed.push((true, bank, off, chip.data.len().min(BANK - off)));
            }
            a => return Err(format!("chip loaded at ${a:04X}, invalid address")),
        }
    }
    for &(high, bank, off, len) in &placed {
        if placed.iter().filter(|p| p.0 == high && p.1 == bank).count() == 1 {
            mirror(if high { &mut cart.romh } else { &mut cart.roml }, bank, off, len);
        }
    }

    cart.bank_mask = if kind.flash() {
        kind.register_mask()
    } else {
        ((highest + 1).next_power_of_two() - 1) as u8 & kind.register_mask()
    };
    // Flash: the whole chip, erased where the CRT has no data
    let flash = |rom: &mut Vec<u8>, chip: Chip| {
        rom.resize(chip.size(), 0xFF);
        Some(Flash::new(chip))
    };
    match kind {
        Kind::EasyFlash => {
            cart.ram = vec![0; 0x100];
            cart.flash_lo = flash(&mut cart.roml, Chip::Am29F040B);
            cart.flash_hi = flash(&mut cart.romh, Chip::Am29F040B);
        }
        Kind::GMod2 => {
            cart.eeprom = Some(M93c86::default());
            cart.flash_lo = flash(&mut cart.roml, Chip::Am29F040);
        }
        Kind::Megabyter => cart.flash_lo = flash(&mut cart.roml, Chip::Mx29F800CB),
        Kind::Rgcd if revision == 1 && ![0, 1, 3, 7].contains(&highest) => {
            return Err(format!("Hucky with {} banks: 1, 2, 4 or 8 required", highest + 1));
        }
        Kind::MagicDeskPlus => {
            // 0: SRAM + 32K EEPROM, 1: SRAM + 8K, 2: 32K, 3: 8K, 4: SRAM only
            let (sram, eeprom) = match revision {
                0 => (true, 0x8000),
                1 => (true, 0x2000),
                2 => (false, 0x8000),
                3 => (false, 0x2000),
                4 => (true, 0),
                r => return Err(format!("Magic Desk Plus: unknown revision {r}")),
            };
            if sram {
                cart.ram = vec![0; MDP_SRAM];
            }
            cart.nv = vec![0xFF; eeprom];
        }
        _ => {}
    }
    cart.reset();
    Ok(cart)
}

// ── Saveable state ───────────────────────────────────────────────────────────

use crate::snapshot::{Reader, Result as StateResult, State, Writer};

crate::snapshot::impl_state_enum!(Mode { Off, Game8K, Game16K, Ultimax });
crate::snapshot::impl_state_enum!(Kind {
    Normal, Ocean, FunPlay, SuperGames, Gs, Dinamic, Zaxxon, MagicDesk, Ross, EasyFlash, Rgcd,
    GMod2, Drean, MagicDesk16, Megabyter, MagicDeskPlus,
});

/// ROMs are saved as a block (length and bytes), not byte by byte.
fn save_bytes(v: &[u8], w: &mut Writer) {
    (v.len() as u32).save(w);
    w.put(v);
}

fn load_bytes(v: &mut Vec<u8>, r: &mut Reader) -> StateResult<()> {
    let mut n = 0u32;
    n.load(r)?;
    *v = r.take(n as usize)?.to_vec();
    Ok(())
}

impl State for CartState {
    fn save(&self, w: &mut Writer) {
        let Self {
            kind, name, revision, roml, romh, roml_bank, romh_bank, mode, boot_mode, regs,
            bank_mask, locked, ram, eeprom, flash_lo, flash_hi, nv, nv_dirty, nvram_path,
        } = self;
        kind.save(w);
        name.save(w);
        revision.save(w);
        save_bytes(roml, w);
        save_bytes(romh, w);
        roml_bank.save(w);
        romh_bank.save(w);
        mode.save(w);
        boot_mode.save(w);
        regs.save(w);
        bank_mask.save(w);
        locked.save(w);
        save_bytes(ram, w);
        eeprom.save(w);
        flash_lo.save(w);
        flash_hi.save(w);
        save_bytes(nv, w);
        nv_dirty.save(w);
        nvram_path.save(w);
    }

    fn load(&mut self, r: &mut Reader) -> StateResult<()> {
        let Self {
            kind, name, revision, roml, romh, roml_bank, romh_bank, mode, boot_mode, regs,
            bank_mask, locked, ram, eeprom, flash_lo, flash_hi, nv, nv_dirty, nvram_path,
        } = self;
        kind.load(r)?;
        name.load(r)?;
        revision.load(r)?;
        load_bytes(roml, r)?;
        load_bytes(romh, r)?;
        roml_bank.load(r)?;
        romh_bank.load(r)?;
        mode.load(r)?;
        boot_mode.load(r)?;
        regs.load(r)?;
        bank_mask.load(r)?;
        locked.load(r)?;
        load_bytes(ram, r)?;
        eeprom.load(r)?;
        flash_lo.load(r)?;
        flash_hi.load(r)?;
        load_bytes(nv, r)?;
        nv_dirty.load(r)?;
        nvram_path.load(r)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// CRT with the given chips: (bank, address, data).
    fn crt(crt_type: u16, exrom: u8, game: u8, revision: u8, chips: &[(u16, u16, Vec<u8>)]) -> Vec<u8> {
        let mut d = b"C64 CARTRIDGE   ".to_vec();
        d.extend(0x40u32.to_be_bytes());
        d.extend([1, 0]);
        d.extend(crt_type.to_be_bytes());
        d.extend([exrom, game, revision]);
        d.resize(0x40, 0);
        for (bank, load, data) in chips {
            d.extend(b"CHIP");
            d.extend((16 + data.len() as u32).to_be_bytes());
            d.extend([0, 0]);
            d.extend(bank.to_be_bytes());
            d.extend(load.to_be_bytes());
            d.extend((data.len() as u16).to_be_bytes());
            d.extend(data);
        }
        d
    }

    #[test]
    fn unsupported_type_is_an_error() {
        let data = crt(1, 0, 1, 0, &[(0, 0x8000, vec![0; 0x2000])]);
        let err = parse_crt(&data).err().unwrap();
        assert!(err.contains("Action Replay"), "{err}");
    }

    #[test]
    fn small_chip_is_mirrored_in_its_window() {
        // 4K Ultimax at $F000: also visible at $E000
        let rom: Vec<u8> = (0..0x1000).map(|i| i as u8).collect();
        let c = parse_crt(&crt(0, 1, 0, 0, &[(0, 0xF000, rom)])).unwrap();
        assert_eq!(c.mode, Mode::Ultimax);
        assert_eq!(c.peek_romh(0x0123), 0x23);
        assert_eq!(c.peek_romh(0x1123), 0x23);
        assert_eq!(c.peek_roml(0), 0xFF, "ROML missing");
    }

    #[test]
    fn magic_desk_plus_sram_and_eeprom() {
        let chips: Vec<_> = (0..32).map(|b| (b, 0x8000, vec![b as u8; 0x2000])).collect();
        // Revision 1: 128K SRAM and 8K EEPROM
        let mut c = parse_crt(&crt(87, 0, 1, 1, &chips)).unwrap();
        assert_eq!((c.mode, c.peek_roml(0)), (Mode::Game8K, 0));
        c.write_io1(0, 0x25); // bank 37: masked to 32 banks
        assert_eq!(c.peek_roml(0), 5);
        c.write_io1(0, 0x80);
        assert_eq!(c.mode, Mode::Off);

        // SRAM: two 64K halves ($DE03 bit 0), page in $DE01
        c.write_io1(3, 0x20);
        c.write_io1(1, 0x12);
        c.write_io2(0x34, 0x77);
        c.write_io1(3, 0x21);
        c.write_io2(0x34, 0x66);
        assert_eq!(c.read_io2(0x34), Some(0x66));
        c.write_io1(3, 0x20);
        assert_eq!(c.read_io2(0x34), Some(0x77));
        assert!(!c.nvram_dirty(), "SRAM is not memory to be saved");

        // 8K EEPROM: 32 pages, page $23 is $03
        c.write_io1(3, 0x00);
        c.write_io1(1, 0x23);
        assert_eq!(c.read_io2(0x10), Some(0xFF), "empty EEPROM");
        c.write_io2(0x10, 0x99);
        c.write_io1(1, 0x03);
        assert_eq!(c.read_io2(0x10), Some(0x99));
        assert!(c.nvram_dirty());
        assert_eq!(c.nvram().len(), 0x2000);
        assert_eq!(c.nvram()[0x310], 0x99);

        // Reset re-enables the ROM at bank 0; the EEPROM is kept
        c.reset();
        assert_eq!((c.mode, c.peek_roml(0)), (Mode::Game8K, 0));
        c.write_io1(1, 0x03);
        assert_eq!(c.read_io2(0x10), Some(0x99));

        // Revision 2: EEPROM only, the SRAM window is open bus
        let mut c = parse_crt(&crt(87, 0, 1, 2, &chips)).unwrap();
        c.write_io1(3, 0x20);
        assert_eq!(c.read_io2(0), None);
    }

    #[test]
    fn nvram_survives_savestate() {
        let mut c = parse_crt(&crt(60, 0, 1, 0, &[(0, 0x8000, vec![1; 0x2000])])).unwrap();
        // EEPROM (2K) and then the whole flash (512K)
        let mut data = c.nvram();
        assert_eq!(data.len(), eeprom::SIZE + 0x80000);
        data[7] = 0x42;
        data[eeprom::SIZE + 0x2005] = 0x77;
        c.load_nvram(&data).unwrap();
        c.write_io1(0, 0x01);
        assert_eq!(c.peek_roml(5), 0x77);
        assert_eq!(c.peek_roml(0x1FFF), 0xFF, "flash erased where the CRT has no data");
        c.write_io1(0, 0x40);
        let mut w = Writer::new();
        c.save(&mut w);
        let mut d = CartState::default();
        d.load(&mut Reader::new(&w.buf)).unwrap();
        assert_eq!((d.kind, d.mode, d.nvram()[7]), (Kind::GMod2, Mode::Off, 0x42));
        assert!(c.load_nvram(&[0; 10]).is_err());
    }
}
