; ROBO NINE - a Commodore 64 intro for 64tass (without -a)
;
; A robot pulls nine digits out of its chest, they circle around it, then
; they line up in the top border: nine digits on the same raster lines,
; although the VIC-II has only eight sprites. Inspired by "Nine" by Linus
; Akesson (lft, 2025); the code and the trick used here are our own.
;
; The ninth digit is not a sprite. In the open border the VIC shows the idle
; byte ($3FFF in bank 0) with black pixels over the background colour. Every
; raster line of the digit writes the inverted glyph row into $3FFF, then
; 4 cycles later sets $D021 back to black: the only 8 pixels fetched with the
; new byte while the background still had the digit's colour are the digit.
; The writes must land on exact cycles although the sprite DMA of every line
; changes as the other digits fly in; a CIA timer that runs in step with the
; raster (63 cycles) tells each line how many cycles to wait.
;
; Data (sprites, robot, tables, music) are generated by gen_data.py.

zp      = $fb           ; player: pointer (2 bytes)
tmp     = $fd
tmp2    = $fe
tmp3    = $02

; --- constants --------------------------------------------------------------
BG      = 6             ; background: blue
XS      = 7             ; fine scroll during the ghost band
GHOSTC  = 26            ; text column of the idle byte with the ghost digit
GHOSTX  = 24 + 8 * GHOSTC + XS + 2   ; its sprite X (the glyph is in bits 5-0)
SLOTDX  = 24            ; distance between the digits of the row
ROWY    = 30            ; sprite Y of the row in the top border
TH      = 20            ; timer value at cycle 11 of a line (see sync_timer)
FILL    = 31 - TH       ; bytes skipped by the smallest wait
BANDH   = 16            ; lines of the ghost digit
GI      = GHOST - 1     ; object index of the ghost digit
SPRBLK  = $e0           ; sprite block of the empty sprite ($3800)
SYNCNOP = 9             ; NOPs before the timer starts (sets its phase)
SYNCBIT = 1             ; and one more 3-cycle instruction
SKIP    = 0             ; testing: first bar of the show (0 = from the start)
BANDOFF = 0             ; raster line of the band interrupt minus sprite Y

SCREEN  = $0400
CHARSET = $3000
SPRMEM  = $3800

; objects (the nine digits): modes and places
M_HIDE  = 0
M_ORBIT = 1
M_SLOT  = 2
M_LERP  = 3
K_CHEST = 0
K_ORBIT = 1
K_SLOT  = 2

; --- zero page --------------------------------------------------------------
        * = $10
frame   .byte ?         ; incremented by the bottom interrupt
fib     .byte ?         ; frame in the bar (0-95)
bar     .byte ?         ; bar of the show
theta   .word ?         ; orbit angle, 8.8
wave    .byte ?         ; 1 while the row does the wave
wphase  .byte ?
ready   .byte ?         ; next frame's sprite data are complete
d016v   .byte ?         ; $D016 of the screen ($08 text, $18 multicolour)
ax      .word ?         ; place A of a lerp
ay      .byte ?
bx      .word ?         ; place B of a lerp
by      .byte ?
px      .word ?         ; result of place/lerp
py      .byte ?
fac1    .byte ?
fac2    .byte ?
neg     .byte ?
dl      .word ?
cnt     .byte ?
look    .byte ?         ; digit the robot looks at ($ff = none)
blink   .byte ?
hatch   .byte ?         ; frames the hatch stays lit
bulb    .byte ?         ; frames the antenna bulb stays yellow
lights  .byte ?         ; rotation of the chest lights
eyeson  .byte ?
ptr     .word ?
nobj    .byte ?         ; sprite objects this frame
order   .fill 9         ; sprite objects sorted by Y
keys    .fill 9         ; their Y
sid     .byte ?
skey    .byte ?
dst     .word ?
pcol    .byte ?

; live values used by the interrupts, copied from the n_ ones
band_on   .byte ?
band_line .byte ?
band_col  .byte ?
mux_on    .byte ?
mux_line  .byte ?
mux_x     .byte ?
mux_xh    .byte ?
mux_y     .byte ?
mux_c     .byte ?
mux_p     .byte ?
spr_en    .byte ?
zpend

; --- program ----------------------------------------------------------------
        * = $0801
        .word (+), 2026
        .null $9e, format("%d", start)
+       .word 0

start   sei
        cld
        ldx #2                  ; keep BASIC's zero page for the way back
-       lda $00,x
        sta zpsave,x
        inx
        bne -
        ldx #$ff
        txs
        lda #$7f                ; no CIA interrupts
        sta $dc0d
        sta $dd0d
        lda $dc0d
        lda $dd0d
        lda #$33                ; character ROM visible: copy chars 0-63
        sta $01
        ldx #0
-       lda $d000,x
        sta CHARSET,x
        lda $d100,x
        sta CHARSET+$100,x
        inx
        bne -
        lda #$35                ; RAM + I/O, no ROMs
        sta $01
        lda #<nmi
        sta $fffa
        lda #>nmi
        sta $fffb

        ldx #0                  ; robot characters
-       lda robchars,x
        sta CHARSET+CHAR0*8,x
        lda robchars+$100,x
        sta CHARSET+CHAR0*8+$100,x
        lda robchars+$200,x
        sta CHARSET+CHAR0*8+$200,x
        inx
        bne -
        ldx #0                  ; sprites: empty + 9 digits
-       lda sprites,x
        sta SPRMEM,x
        lda sprites+$100,x
        sta SPRMEM+$100,x
        lda sprites+$200,x
        sta SPRMEM+$200,x
        inx
        bne -
        lda #$ff                ; idle byte: all black
        sta $3fff

        ldx #0                  ; clear screen and colours
-       lda #$20
        sta SCREEN,x
        sta SCREEN+$100,x
        sta SCREEN+$200,x
        sta SCREEN+$2e8,x
        lda #BG
        sta $d800,x
        sta $d900,x
        sta $da00,x
        sta $dae8,x
        inx
        bne -

        ldx #$2e                ; VIC
-       lda vicinit,x
        sta $d000,x
        dex
        bpl -
        lda #$1c                ; screen $0400, characters $3000
        sta $d018

        ldx #zpend-frame-1      ; variables
        lda #0
-       sta frame,x
        dex
        bpl -
        lda #$ff
        sta look
        lda #$08                ; text mode until the robot appears
        sta d016v
        lda #<txt_presents      ; bar 0: title
        ldx #>txt_presents
        jsr print
        ldx #8
-       lda #M_HIDE
        sta omode,x
        dex
        bpl -
        ldx #$18                ; SID
        lda #0
-       sta $d400,x
        dex
        bpl -
        jsr init
        .if SKIP                ; testing: start with the row in the border
        jsr draw_robot
        lda #$18
        sta d016v
        lda #1
        sta eyeson
        lda #SKIP
        sta bar
        lda #95
        sta fib
        ldx #8
-       lda #M_SLOT
        sta omode,x
        dex
        bpl -
        .endif

        jsr sync_timer

        lda #<irq_bot
        sta $fffe
        lda #>irq_bot
        sta $ffff
        lda #249
        sta $d012
        lda #$1b
        sta $d011
        lda #1
        sta $d01a
        sta $d019
        cli

; main loop: after the bottom interrupt prepares the next frame
mainlp  lda frame
-       cmp frame
        beq -
        jsr step
        jmp mainlp

nmi     rti

; --- start CIA1 timer A in step with the raster ------------------------------
; A double interrupt gives a stable raster position; the timer then runs
; forever with a period of one line, so its value tells the raster cycle.
sync_timer
        lda #62
        sta $dc04
        lda #0
        sta $dc05
        lda #<irq_s1
        sta $fffe
        lda #>irq_s1
        sta $ffff
        lda #100
        sta $d012
        lda #$1b
        sta $d011
        lda #1
        sta $d01a
        sta $d019
        lda #0
        sta cnt
        cli
-       lda cnt
        beq -
        sei
        rts

irq_s1  lda #<irq_s2
        sta $fffe
        lda #>irq_s2
        sta $ffff
        inc $d012
        asl $d019
        tsx
        cli
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
        nop
irq_s2  txs                     ; 0 or 1 cycle of jitter here
        ldx #8
-       dex
        bne -
        bit $00
        lda $d012
        cmp $d012
        beq +                   ; one more cycle if the line has not changed
+       .fill SYNCNOP, $ea      ; tuning: puts the timer in phase
        .if SYNCBIT
        bit $ea
        .endif
        lda #$11                ; force load, start, continuous
        sta $dc0e
        asl $d019
        inc cnt
        rti

; --- interrupts -------------------------------------------------------------
; line 249: open the lower (and so the upper) border, set up the sprites of
; the next frame, play the music, choose the next interrupt
irq_bot sta bra+1
        stx brx+1
        sty bry+1
        lda #$13                ; 24 rows: the border does not start at line 251
        sta $d011
        lda #0                  ; no sprites in the lower border: a Y below 56
        sta $d015               ; would show them again 256 lines later
        lda #1
        sta $d019
        lda ready
        bne +
        jmp noupd
+
        ldx #7
-       lda n_c,x
        sta $d027,x
        lda n_p,x
        sta SCREEN+$3f8,x
        dex
        bpl -
        .for i = 0, i < 8, i += 1
        lda n_x+i
        sta $d000+2*i
        lda n_y+i
        sta $d001+2*i
        .next
        lda n_msb
        sta $d010
        lda n_en
        sta spr_en
        ldx #n_end-n_band-1
-       lda n_band,x
        sta band_on,x
        dex
        bpl -
        lda #0
        sta ready
noupd
-       lda $d011               ; back to 25 rows after line 251
        bmi +
        lda $d012
        cmp #252
        bcc -
+       lda #$1b
        sta $d011
        lda d016v
        sta $d016
        jsr play
        inc frame
        lda #<irq_top
        ldx #>irq_top
        ldy #5
        jmp setirq

; line 5: sprites on, then the next interrupt of the frame
irq_top sta bra+1
        stx brx+1
        sty bry+1
        lda spr_en
        sta $d015
        lda #1
        sta $d019
        jmp nextirq

; line 22 below the top sprite: reuse sprite 0 for the ninth object
irq_mux sta bra+1
        stx brx+1
        sty bry+1
        lda mux_y
        sta $d001
        lda mux_x
        sta $d000
        lda $d010
        and #$fe
        ora mux_xh
        sta $d010
        lda mux_c
        sta $d027
        lda mux_p
        sta SCREEN+$3f8
        lda #1
        sta $d019
        lda #<irq_bot
        ldx #>irq_bot
        ldy #249
        jmp setirq

; next interrupt after the bottom one: ghost band, sprite reuse or bottom
nextirq lda band_on
        beq +
        lda #<irq_band
        ldx #>irq_band
        ldy band_line
        jmp setirq
+       lda mux_on
        beq +
        lda #<irq_mux
        ldx #>irq_mux
        ldy mux_line
        jmp setirq
+       lda #<irq_bot
        ldx #>irq_bot
        ldy #249
setirq  sta $fffe
        stx $ffff
        sty $d012
bra     lda #0
brx     ldx #0
bry     ldy #0
        rti

; the line before the ghost digit: draw it, one raster line per block.
; Each block waits until the timer says cycle 11-19 (the sprite DMA of the
; line is over by then), then waits 10-2 more cycles to land on cycle 35:
;   cycle 40: $3FFF = glyph row    (fetched at 41 = column 26)
;   cycle 44: $D021 = black        (the digit's colour covered 8+2 pixels)
;   cycle 48: $3FFF = $FF, cycle 55: $D021 = digit colour for the next line
; A write at cycle 55 is still allowed when the sprite DMA starts, so after
; it the CPU only has the next block's timer read to do.
irq_band
        sta bra+1
        stx brx+1
        sty bry+1
        lda #0                  ; the scroll change leaves a few background
        sta $d021               ; pixels: black
        lda #XS                 ; hires (the idle byte must not be multicolour),
        sta $d016               ; 38 columns (covers the pixels left by the scroll)
        lda band_col
        sta $d021
        ldx #$ff                ; all black
        ldy #0                  ; black
        .for i = 0, i < BANDH, i += 1
        .block
        .if (* & $ff) > $100 - 8 || ((* + 12) & $ff) > $100 - 2 - 20
        jmp +                   ; the branches must not cross a page
        .align $100
+
        .endif
wait    lda $dc04
        cmp #TH+1
        bcs wait
        eor #$1f                ; 31 - timer: skip more when later
        sta br+1
br      bpl *+2
        .fill FILL, $ea         ; never executed
        .byte $c9, $c9, $c9, $c9, $c9, $c9, $c9, $c5, $ea
        lda #GPAT[i]
        sta $3fff               ; glyph row
        sty $d021               ; black
        stx $3fff               ; all black again
        lda band_col
        sta $d021               ; digit colour
        .bend
        .next
        sty $d021               ; black while the scroll changes back
        lda d016v
        sta $d016
        lda #BG
        sta $d021
        lda #1
        sta $d019
        lda #<irq_bot
        ldx #>irq_bot
        ldy #249
        jmp setirq

; --- one frame of the show (main loop) ----------------------------------------
step    jsr clock
        jsr script
        jsr fade
        jsr robot
        jsr places
        jsr sprites_out
        rts

clock   inc fib
        lda fib
        cmp #96
        bcc +
        lda #0
        sta fib
        inc bar
+       lda theta               ; the orbit turns 2 units per frame
        clc
        adc #$00
        sta theta
        lda theta+1
        adc #2
        sta theta+1
        lda wave
        beq +
        inc wphase
+       rts

; events of the show, on the first frame of a bar and in the middle of it
script  lda fib
        beq onbar
        cmp #48
        beq onhalf
        rts

onhalf  lda bar
        cmp #2                  ; bar 2.5: the robot wakes up
        bne +
        lda #1
        sta eyeson
        rts
+       cmp #46                 ; bars 46.5-49.5: digits 2, 4, 6, 8 go home
        bcc +
        cmp #50
        bcs +
        sbc #46-1               ; carry clear: A - 46
        asl a
        ora #1
        tax
        jmp absorb
+       rts

onbar   lda bar
        cmp #2                  ; bar 2: the robot
        bne +
        lda #12
        jsr clearrow
        jsr draw_robot
        lda #$18
        sta d016v
        rts
+       cmp #3                  ; bars 3-11: digits 1-9 come out
        bcc +
        cmp #12
        bcs +
        sbc #3-1                ; carry clear: A - 3
        tax
        lda #24
        sta hatch
        lda #K_CHEST
        ldy #K_ORBIT
        jmp startlerp
+       cmp #16                 ; bars 16-24: digits 1-9 fly to the row
        bcc +
        cmp #25
        bcs +
        sbc #16-1
        tax
        lda #K_ORBIT
        ldy #K_SLOT
        jmp startlerp
+       cmp #25                 ; bar 25: the wave and the captions
        bne +
        lda #1
        sta wave
        lda #0
        sta wphase
        lda #<txt_nine
        ldx #>txt_nine
        jsr print
        lda #<txt_eight
        ldx #>txt_eight
        jmp print
+       cmp #33                 ; bar 33: the wave stops
        bne +
        lda #0
        sta wave
        lda #21
        jsr clearrow
        lda #23
        jsr clearrow
        lda bar
+       cmp #33                 ; bars 33-41: back to the orbit, 9 first
        bcc +
        cmp #42
        bcs +
        eor #$ff                ; 41 - bar
        sec
        adc #41
        tax
        lda #K_SLOT
        ldy #K_ORBIT
        jmp startlerp
+       cmp #46                 ; bars 46-50: digits 1, 3, 5, 7, 9 go home
        bcc +
        cmp #51
        bcs +
        sbc #46-1
        asl a
        tax
        jmp absorb
+       cmp #51                 ; bar 51: the robot switches off
        bne +
        lda #0
        sta eyeson
        rts
+       cmp #52                 ; bar 52: back to BASIC
        bne +
        jmp tobasic
+       rts

; bar 51: the music fades out (volume 15 to 0 in 96 frames)
fade    lda bar
        cmp #51
        bne ++
        ldx #15
        lda fib
-       sec
        sbc #6
        bcc +
        dex
        bne -
+       txa
        ora #$10                ; low-pass filter, as the player sets it
        sta $d418
+       rts

; the end: machine as at power-on, program still in memory, READY.
tobasic sei
        lda #0
        sta $d01a               ; no raster interrupts
        sta $d015
        lda #$ff
        sta $d019
        ldx #$18                ; SID silent
        lda #0
-       sta $d400,x
        dex
        bpl -
        ldx #2                  ; BASIC's zero page back
-       lda zpsave,x
        sta $00,x
        inx
        bne -
        lda #$37                ; BASIC and KERNAL ROMs
        sta $01
        jsr $fda3               ; IOINIT: CIAs, KERNAL timer interrupt
        jsr $ff81               ; CINT: VIC and screen editor, clears the screen
        jmp ($a002)             ; BASIC warm start: READY.

absorb  lda #K_ORBIT
        ldy #K_CHEST
        jsr startlerp
        lda #24
        sta hatch
        rts

; object X: lerp from place A to place Y
startlerp
        sta oa,x
        tya
        sta ob,x
        lda #M_LERP
        sta omode,x
        lda #0
        sta ot,x
        stx look
        rts

; --- robot ------------------------------------------------------------------
ROBS    = SCREEN + ROBOT_ROW * 40 + ROBOT_COL
ROBC    = $d800 + ROBOT_ROW * 40 + ROBOT_COL

draw_robot
        lda #<ROBS
        sta ptr
        lda #>ROBS
        sta ptr+1
        ldx #0
drrow   ldy #0
-       lda robscr,x
        sta (ptr),y
        lda ptr+1               ; colour RAM: same offset from $D800
        pha
        clc
        adc #>($d800-SCREEN)
        sta ptr+1
        lda robcol,x
        sta (ptr),y
        pla
        sta ptr+1
        inx
        iny
        cpy #6
        bne -
        lda ptr
        clc
        adc #40
        sta ptr
        bcc +
        inc ptr+1
+       cpx #60
        bne drrow
        rts

; per frame: eyes (off, looking, blinking), hatch, antenna bulb, chest lights
robot   lda bar
        cmp #2
        bcs +
        rts
+       lda beat                ; drums from the player
        beq nobeat
        cmp #2
        bne +
        lda #6                  ; snare: bulb yellow
        sta bulb
+       inc lights
        lda #0
        sta beat
nobeat  lda #8|2                ; antenna bulb
        ldx bulb
        beq +
        dec bulb
        lda #8|7
+       sta ROBC+2
        sta ROBC+3
        lda #8|0                ; hatch: lit while a digit comes or goes
        ldx hatch
        beq +
        dec hatch
        lda #8|7
+       sta ROBC+5*40+2
        sta ROBC+5*40+3
        lda lights              ; chest lights rotate on every drum
        and #3
        tax
        ldy #0
-       lda lightcol,x
        sta ROBC+6*40+1,y
        inx
        iny
        cpy #4
        bne -
        lda eyeson              ; eyes: off until bar 2.5, then cyan
        beq eyesoff
        inc blink
        ldx #3
        lda blink
        cmp #6
        bcc eyeset
        cmp #150
        bcc +
        lda #0
        sta blink
+       ldx #0                  ; look at the moving digit
        ldy look
        bmi eyeset
        lda omode,y
        cmp #M_LERP
        beq +
        lda #$ff
        sta look
        bne eyeset
+       lda oxh,y
        bne lookr
        lda oxl,y
        cmp #150
        bcc lookl
        cmp #212
        bcc eyeset
lookr   ldx #2
        bne eyeset
lookl   ldx #1
eyeset  lda eyel,x
        sta ROBS+2*40+1
        lda eyer,x
        sta ROBS+2*40+4
        lda #8|3
        bne +
eyesoff lda #8|0
+       sta ROBC+2*40+1
        sta ROBC+2*40+4
        rts

lightcol .byte 8|2, 8|7, 8|5, 8|3, 8|2, 8|7, 8|5

; --- places of the digits ---------------------------------------------------
places  ldx #8
-       stx cnt
        jsr place1
        ldx cnt
        dex
        bpl -
        rts

place1  lda omode,x
        cmp #M_LERP
        beq plerp
        cmp #M_HIDE
        beq +
where1  jsr where               ; orbit or slot (= place kind): straight there
        ldx cnt
        lda px
        sta oxl,x
        lda px+1
        sta oxh,x
        lda py
        sta oy,x
+       rts

plerp   lda ot,x                ; last step: exactly at B
        cmp #64
        bcc +
        lda ob,x
        tay
        lda endmode,y
        sta omode,x
        tya
        jmp where1
+       lda oa,x                ; A
        jsr where
        lda px
        sta ax
        lda px+1
        sta ax+1
        lda py
        sta ay
        ldx cnt
        lda ob,x                ; B
        jsr where
        ldx cnt
        ldy ot,x
        lda ease,y
        sta fac2
        lda px                  ; x = A + (B - A) * e
        sec
        sbc ax
        sta dl
        lda px+1
        sbc ax+1
        sta dl+1
        jsr lerp
        lda dl
        clc
        adc ax
        sta oxl,x
        lda dl+1
        adc ax+1
        sta oxh,x
        lda py                  ; y
        sec
        sbc ay
        sta dl
        lda #0
        sbc #0
        sta dl+1
        jsr lerp
        lda dl
        clc
        adc ay
        sta oy,x
        inc ot,x
        rts

endmode .byte M_HIDE, M_ORBIT, M_SLOT

; place of kind A for object cnt -> px, py
where   ldx cnt
        cmp #K_ORBIT
        beq wo
        cmp #K_SLOT
        beq ws
        lda #<CHESTX            ; chest
        sta px
        lda #>CHESTX
        sta px+1
        lda #CHESTY
        sta py
        rts
wo      lda theta+1
        clc
        adc slotang,x
        tay
        lda orbxl,y
        sta px
        lda orbxh,y
        sta px+1
        lda orby,y
        sta py
        rts
ws      lda slotxl,x
        sta px
        lda slotxh,x
        sta px+1
        lda #ROWY
        ldy wave
        beq +
        txa                     ; wave: each digit 4 frames after the previous
        asl a
        asl a
        eor #$ff
        sec
        adc wphase
        and #63
        tay
        lda #ROWY
        sec
        sbc hop,y
+       sta py
        rts

; dl = dl * fac2 / 256, dl signed (-511..511), fac2 0-255. Keeps X.
lerp    lda dl+1
        sta neg
        bpl +
        lda #0
        sec
        sbc dl
        sta dl
        lda #0
        sbc dl+1
        sta dl+1
+       lda dl
        sta fac1
        lda #0                  ; fac1 * fac2 -> A:fac1
        ldy #8
        lsr fac1
-       bcc +
        clc
        adc fac2
+       ror a
        ror fac1
        dey
        bne -
        ldy dl+1                ; + 256 * fac2 / 256 when |dl| >= 256
        beq +
        clc
        adc fac2
        sta dl
        lda #0
        adc #0
        sta dl+1
        jmp ++
+       sta dl
        lda #0
        sta dl+1
+       lda neg
        bpl +
        lda #0
        sec
        sbc dl
        sta dl
        lda #0
        sbc dl+1
        sta dl+1
+       ldx cnt
        rts

; angle of each digit on the orbit (1/9 of a turn apart) and its row slot
slotang .byte 0, 28, 57, 85, 114, 142, 171, 199, 228
SLOTX   = GHOSTX + (range(9) - GI) * SLOTDX
slotxl  .byte <SLOTX
slotxh  .byte >SLOTX
digcol  .byte 10, 8, 7, 13, 5, 3, 14, 4, 1

; --- sprites of the next frame ------------------------------------------------
; Objects that are not hidden (and the ghost digit when it sits in its slot)
; are sorted by Y; eight go to the sprites, a ninth reuses sprite 0 below
; the first one.
sprites_out
        lda ready               ; the interrupt has not taken the last ones
        beq +
        rts
+
        ldx #0
        ldy #0
        sty n_band
-       lda omode,x
        beq next
        cpx #GI
        bne +
        cmp #M_SLOT
        bne +
        lda #1                  ; ghost digit in its slot: not a sprite
        sta n_band
        lda oy,x
        clc
        adc #BANDOFF
        sta n_bline
        lda digcol,x
        sta n_bcol
        jmp next
+       txa
        sta order,y
        lda oy,x
        sta keys,y
        iny
next    inx
        cpx #9
        bne -
        sty nobj
        ; insertion sort by Y
        ldx #1
s_outer cpx nobj
        bcs sorted
        lda order,x
        sta sid
        lda keys,x
        sta skey
        txa
        tay
s_in    lda keys-1,y
        cmp skey
        bcc s_put
        beq s_put
        sta keys,y
        lda order-1,y
        sta order,y
        dey
        bne s_in
s_put   lda skey
        sta keys,y
        lda sid
        sta order,y
        inx
        jmp s_outer
sorted  lda #0
        sta n_msb
        sta n_mux
        ldx #0                  ; x = sprite
-       cpx nobj
        bcs spoff
        cpx #8
        bcs spoff
        ldy order,x
        lda oxl,y
        sta n_x,x
        lda oxh,y
        beq +
        lda bitval,x
        ora n_msb
        sta n_msb
+       lda oy,y
        sta n_y,x
        lda digcol,y
        sta n_c,x
        tya
        clc
        adc #SPRBLK+1
        sta n_p,x
        inx
        bne -
spoff   lda enmask,x
        sta n_en
        lda nobj                ; a ninth sprite object: reuse sprite 0
        cmp #9
        bcc sprok
        ldy order
        lda oy,y
        clc
        adc #22
        sta n_mline
        ldy order+8
        lda oy,y
        sec
        sbc n_mline
        bcc sprok               ; too close: the ninth waits (never here)
        cmp #3
        bcc sprok
        lda #1
        sta n_mux
        lda oy,y
        sta n_my
        lda oxl,y
        sta n_mx
        lda oxh,y
        sta n_mxh
        lda digcol,y
        sta n_mc
        tya
        clc
        adc #SPRBLK+1
        sta n_mp
sprok   lda #1
        sta ready
sprdone rts

bitval  .byte 1, 2, 4, 8, 16, 32, 64, 128
enmask  .byte 0, 1, 3, 7, 15, 31, 63, 127, 255

; --- text -------------------------------------------------------------------
; A/X = record: screen offset (word), colour, screen codes ending with 0
print   sta ptr
        stx ptr+1
        ldy #0
        lda (ptr),y
        clc
        adc #<SCREEN
        sta dst
        iny
        lda (ptr),y
        adc #>SCREEN
        sta dst+1
        iny
        lda (ptr),y
        sta pcol
        lda ptr
        clc
        adc #3
        sta ptr
        bcc +
        inc ptr+1
+       ldy #0
-       lda (ptr),y
        beq +
        sta (dst),y
        lda dst+1
        pha
        clc
        adc #>($d800-SCREEN)
        sta dst+1
        lda pcol
        sta (dst),y
        pla
        sta dst+1
        iny
        bne -
+       rts

; A = row: fill it with spaces
clearrow
        tax
        lda rowlo,x
        sta dst
        lda rowhi,x
        sta dst+1
        ldy #39
        lda #$20
-       sta (dst),y
        dey
        bpl -
        rts

rowlo   .byte <(SCREEN + range(25) * 40)
rowhi   .byte >(SCREEN + range(25) * 40)

        .enc "screen"
txt_presents .word 12*40+11
        .byte 15
        .null "SAMPOSOFT PRESENTS"
txt_nine .word 21*40+9
        .byte 1
        .null "NINE DIGITS, ONE LINE"
txt_eight .word 23*40+6
        .byte 7
        .null "THE VIC-II HAS EIGHT SPRITES"
        .enc "none"

; --- VIC ----------------------------------------------------------------------
vicinit .fill 16, 0             ; sprite positions
        .byte 0                 ; $d010
        .byte $1b, 249, 0, 0    ; $d011-$d014
        .byte 0                 ; $d015
        .byte $08               ; $d016
        .byte 0                 ; $d017
        .byte $1c               ; $d018
        .byte $ff, 0            ; $d019, $d01a
        .byte 0, 0, 0, 0        ; $d01b-$d01e
        .byte 0                 ; $d01f
        .byte 0, BG             ; $d020, $d021
        .byte 15, 12, 0         ; $d022-$d024
        .byte 0, 0              ; $d025, $d026
        .fill 8, 1              ; $d027-$d02e

        .include "player.asm"
        .include "data.asm"

; --- variables --------------------------------------------------------------
omode   .fill 9
oa      .fill 9
ob      .fill 9
ot      .fill 9
oxl     .fill 9                 ; x, low byte
oxh     .fill 9                 ; x, high byte
oy      .fill 9

; next frame (written by the main loop, read by the bottom interrupt)
n_x     .fill 8
n_y     .fill 8
n_c     .fill 8
n_p     .fill 8
n_msb   .byte ?
n_en    .byte ?
n_band                          ; same order as band_on ... mux_p
n_bon   = n_band
        .byte ?
n_bline .byte ?
n_bcol  .byte ?
n_mux   .byte ?
n_mline .byte ?
n_mx    .byte ?
n_mxh   .byte ?
n_my    .byte ?
n_mc    .byte ?
n_mp    .byte ?
n_end
zpsave  .fill 256               ; BASIC's zero page while the intro runs

        .cerror * > CHARSET, "the program runs into the character set"

