// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 SampoSoft - Francesco Sampoli

//! winit-specific parts, shared by `c64` and `c64dbg --window`: physical key
//! mapping, window attributes and icon, drawing of the framebuffer with the
//! status bar below it (`Display`: GPU or CPU), capture of the host mouse for the paddles
//! and the 1351 mouse.

use std::num::NonZeroU32;
use std::sync::Arc;

use winit::dpi::LogicalSize;
use winit::event::MouseButton;
use winit::keyboard::{KeyCode, PhysicalKey};
use winit::window::{CursorGrabMode, Icon, Window, WindowAttributes};

use crate::ctrlport::Button;
use crate::keyboard::HostKey;
use crate::vic::{HEIGHT, WIDTH};

/// Identifier of a physical key, to pair the release of a printable key
/// with the character its press produced (`KeyMatrix::char_down/char_up`).
pub fn key_id(key: &PhysicalKey) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    key.hash(&mut h);
    h.finish()
}

/// Maps winit physical keys to non-printable host keys.
pub fn host_key(code: KeyCode) -> Option<HostKey> {
    Some(match code {
        KeyCode::Backspace => HostKey::Backspace,
        KeyCode::Delete => HostKey::Delete,
        KeyCode::Enter | KeyCode::NumpadEnter => HostKey::Return,
        KeyCode::Tab => HostKey::Tab,
        KeyCode::Escape => HostKey::Escape,
        KeyCode::Space => HostKey::Space,
        KeyCode::Home => HostKey::Home,
        KeyCode::ArrowLeft => HostKey::Left,
        KeyCode::ArrowRight => HostKey::Right,
        KeyCode::ArrowUp => HostKey::Up,
        KeyCode::ArrowDown => HostKey::Down,
        KeyCode::F1 => HostKey::F1,   KeyCode::F2 => HostKey::F2,
        KeyCode::F3 => HostKey::F3,   KeyCode::F4 => HostKey::F4,
        KeyCode::F5 => HostKey::F5,   KeyCode::F6 => HostKey::F6,
        KeyCode::F7 => HostKey::F7,   KeyCode::F8 => HostKey::F8,
        KeyCode::F9 => HostKey::F9,   KeyCode::F10 => HostKey::F10,
        KeyCode::F11 => HostKey::F11, KeyCode::F12 => HostKey::F12,
        KeyCode::ShiftLeft => HostKey::LShift,
        KeyCode::ShiftRight => HostKey::RShift,
        KeyCode::ControlLeft => HostKey::LCtrl,
        KeyCode::ControlRight => HostKey::RCtrl,
        KeyCode::AltLeft => HostKey::LAlt,
        KeyCode::AltRight => HostKey::RAlt,
        _ => return None,
    })
}

/// Window attributes: 2x the VIC resolution plus the status bar, at least
/// 1x.
pub fn window_attributes(title: &str) -> WindowAttributes {
    let h = HEIGHT + super::status::BAR_HEIGHT;
    winit::window::Window::default_attributes()
        .with_title(title)
        .with_inner_size(LogicalSize::new((WIDTH * 2) as f64, (h * 2) as f64))
        .with_min_inner_size(LogicalSize::new(WIDTH as f64, h as f64))
}

/// Application icon, generated by `tools/make_icon.py`.
const ICON_PNG: &[u8] = include_bytes!("../../assets/icon.png");
const ICON_RGBA: &[u8] = include_bytes!("../../assets/icon64.rgba");
const ICON_RGBA_SIDE: u32 = 64;

/// Sets the application icon: on the window (Windows, X11; Wayland uses
/// the one from the .desktop file) and in the Dock on macOS, where winit
/// ignores the window icon. To be called on the main thread.
pub fn set_app_icon(window: &Window) {
    if let Ok(icon) = Icon::from_rgba(ICON_RGBA.to_vec(), ICON_RGBA_SIDE, ICON_RGBA_SIDE) {
        window.set_window_icon(Some(icon));
    }
    #[cfg(target_os = "macos")]
    {
        use objc2::rc::Retained;
        use objc2::ClassType;
        use objc2_app_kit::{NSApplication, NSImage};
        use objc2_foundation::{MainThreadMarker, NSData};

        let Some(mtm) = MainThreadMarker::new() else { return };
        let data = NSData::with_bytes(ICON_PNG);
        let image: Option<Retained<NSImage>> = NSImage::initWithData(NSImage::alloc(), &data);
        if let Some(image) = image {
            let app = NSApplication::sharedApplication(mtm);
            // SAFETY: valid image, called on the main thread
            unsafe { app.setApplicationIconImage(Some(&image)) };
        }
    }
    #[cfg(not(target_os = "macos"))]
    let _ = ICON_PNG;
}

/// Area of an image in the window: top-left corner and size of one C64
/// pixel, in physical pixels.
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub sx: f64,
    pub sy: f64,
}

impl Rect {
    /// Window point in pixels of the image (outside it too).
    fn to_image(&self, x: f64, y: f64) -> (i32, i32) {
        (((x - self.x) / self.sx).floor() as i32, ((y - self.y) / self.sy).floor() as i32)
    }
}

/// Position of the C64 screen and of the status bar in the window.
#[derive(Clone, Copy, Default, Debug, PartialEq)]
pub struct Placement {
    pub screen: Rect,
    pub bar: Option<Rect>,
    /// Lines of the screen: 284 PAL, 253 NTSC (`timing::Standard`).
    pub rows: usize,
    /// With the CRT emulation, the screen of the set (x0, y0, x1, y1): the
    /// part of the C64 screen that shows, less than all of it on a TV that
    /// overscans.
    pub tube: Option<[f64; 4]>,
}

impl Placement {
    /// Window point (physical pixels) in C64 pixels, from the top-left
    /// corner of the screen, also outside it (negative or beyond the
    /// edges); points on the status bar come after the screen lines
    /// (y >= `rows`). None only before the first drawing.
    pub fn to_image_signed(&self, x: f64, y: f64) -> Option<(i32, i32)> {
        if self.screen.sx == 0.0 {
            return None;
        }
        if let Some(bar) = &self.bar {
            let (bx, by) = bar.to_image(x, y);
            if by >= 0 {
                return Some((bx, self.rows as i32 + by));
            }
        }
        Some(self.screen.to_image(x, y))
    }
}

/// How the CRT emulation shows the screen: the aspect of its pixels
/// (narrower than tall: 0.936 PAL, 0.75 NTSC) and the part of it on the
/// set's screen (fractions of width and height, centred: 1 on a monitor).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CrtShape {
    pub aspect: f64,
    pub visible: (f64, f64),
}

/// Where the screen (`rows` lines) and the bar go in a `dw`×`dh` window: the
/// same integer scale for both, centered, one above the other. With the CRT
/// emulation (`crt`) the screen pixels have its aspect and only its visible
/// part is placed (the rest falls outside `tube`); without the bar
/// (fullscreen) the CRT screen then fills the window at any scale.
pub fn layout(dw: usize, dh: usize, rows: usize, bar: bool, crt: Option<CrtShape>) -> Placement {
    let bar_h = if bar { super::status::BAR_HEIGHT } else { 0 };
    let Some(shape) = crt else {
        let scale = (dw / WIDTH).min(dh / (rows + bar_h)).max(1);
        let x0 = dw.saturating_sub(WIDTH * scale) / 2;
        let y0 = dh.saturating_sub((rows + bar_h) * scale) / 2;
        let s = scale as f64;
        let screen = Rect { x: x0 as f64, y: y0 as f64, sx: s, sy: s };
        let bar = bar.then_some(Rect { x: x0 as f64, y: (y0 + rows * scale) as f64, sx: s, sy: s });
        return Placement { screen, bar, rows, tube: None };
    };
    // Size of the visible part in C64 pixels
    let (vw, vh) = (WIDTH as f64 * shape.visible.0, rows as f64 * shape.visible.1);
    let aspect = shape.aspect;
    let (x, y, sy, bar_rect) = if bar {
        let scale = ((dw as f64 / WIDTH as f64).min(dh as f64 / (vh + bar_h as f64)).floor()).max(1.0);
        let (bx, h) = (((dw as f64 - WIDTH as f64 * scale) / 2.0).max(0.0).floor(), vh * scale + bar_h as f64 * scale);
        let y = ((dh as f64 - h) / 2.0).max(0.0).floor();
        let x = ((dw as f64 - vw * aspect * scale) / 2.0).floor();
        (x, y, scale, Some(Rect { x: bx, y: y + (vh * scale).round(), sx: scale, sy: scale }))
    } else {
        let sy = (dh as f64 / vh).min(dw as f64 / (vw * aspect));
        let (w, h) = (vw * aspect * sy, vh * sy);
        (((dw as f64 - w) / 2.0).floor(), ((dh as f64 - h) / 2.0).floor(), sy, None)
    };
    let sx = sy * aspect;
    let tube = [x, y, x + vw * sx, y + vh * sy];
    // The whole screen, centred on the visible part
    let screen = Rect {
        x: x - WIDTH as f64 * (1.0 - shape.visible.0) / 2.0 * sx,
        y: y - rows as f64 * (1.0 - shape.visible.1) / 2.0 * sy,
        sx,
        sy,
    };
    Placement { screen, bar: bar_rect, rows, tube: Some(tube) }
}

/// Draws `screen` and, below it, `bar` (both WIDTH wide, any height) into `buf`
/// (dw×dh) with integer nearest-neighbour scaling, centered, on a black
/// background: the drawing of the window without the GPU.
pub fn blit_scaled(buf: &mut [u32], dw: usize, dh: usize, screen: &[u32], bar: Option<&[u32]>) -> Placement {
    let placement = layout(dw, dh, screen.len() / WIDTH, bar.is_some(), None);
    let scale = placement.screen.sx as usize;
    let (x0, y0) = (placement.screen.x as usize, placement.screen.y as usize);
    let sw = WIDTH * scale;
    buf.fill(0);
    let rows = screen.chunks_exact(WIDTH).chain(bar.unwrap_or(&[]).chunks_exact(WIDTH));
    for (sy, src) in rows.enumerate() {
        for y in sy * scale..(sy + 1) * scale {
            if y0 + y >= dh {
                return placement;
            }
            let dst = &mut buf[(y0 + y) * dw + x0..(y0 + y) * dw + x0 + sw.min(dw - x0)];
            for (x, px) in dst.iter_mut().enumerate() {
                *px = src[x / scale] & 0x00FF_FFFF;
            }
        }
    }
    placement
}

/// What the window shows of the C64 screen with the CRT emulation.
#[derive(Clone, Copy, Debug)]
pub struct CrtView {
    pub crt: crate::crt::Crt,
    /// The machine's VIC-II: its standard, its colors and lumas.
    pub chip: crate::vic::Chip,
    /// Frame blending (`C64::set_blend`), done by the GPU: the screen
    /// passed to `Display::draw` is then the last frame as the VIC drew it.
    pub blend: bool,
    /// Number of the frame (`C64::frame_count`): its parity sets the phase
    /// of the NTSC subcarrier, which alternates from frame to frame.
    pub frame: u64,
    /// HDR output (`C64::set_hdr`), where the display has it.
    pub hdr: bool,
}

/// Drawing surface of a window: the GPU (wgpu, needed for the CRT
/// emulation) or, when there is none or without the `gpu` feature, the
/// CPU (softbuffer).
pub struct Display {
    kind: DisplayKind,
    /// CRT emulation asked for without the GPU: said once.
    warned: bool,
}

enum DisplayKind {
    #[cfg(feature = "gpu")]
    Gpu(super::gpu::WindowRenderer),
    Soft(softbuffer::Surface<Arc<Window>, Arc<Window>>),
}

impl Display {
    pub fn new(window: Arc<Window>) -> Display {
        #[cfg(feature = "gpu")]
        match super::gpu::WindowRenderer::new(window.clone()) {
            Ok(r) => return Display { kind: DisplayKind::Gpu(r), warned: false },
            Err(e) => crate::notice!("WARN: no GPU ({e}): the window is drawn by the CPU, without the CRT emulation."),
        }
        let context = softbuffer::Context::new(window.clone()).expect("softbuffer context");
        let surface = softbuffer::Surface::new(&context, window).expect("softbuffer surface");
        Display { kind: DisplayKind::Soft(surface), warned: false }
    }

    /// Draws the C64 screen and the bar (if any) in the window, of size
    /// `size` (physical pixels); None if the window cannot be drawn now.
    pub fn draw(&mut self, size: (u32, u32), screen: &[u32], bar: Option<&[u32]>, crt: Option<CrtView>) -> Option<Placement> {
        let (Some(w), Some(h)) = (NonZeroU32::new(size.0), NonZeroU32::new(size.1)) else { return None };
        match &mut self.kind {
            #[cfg(feature = "gpu")]
            DisplayKind::Gpu(r) => r.draw(size, screen, bar, crt),
            DisplayKind::Soft(surface) => {
                if crt.is_some() && !self.warned {
                    self.warned = true;
                    crate::notice!("WARN: the CRT emulation needs the GPU.");
                }
                surface.resize(w, h).ok()?;
                let mut buf = surface.buffer_mut().ok()?;
                let placement = blit_scaled(&mut buf, size.0 as usize, size.1 as usize, screen, bar);
                buf.present().ok()?;
                Some(placement)
            }
        }
    }
}

/// Devices in the control ports that the window drives with the host mouse.
#[derive(Clone, Copy, Default)]
pub struct Analog {
    pub paddles: bool,
    pub mouse: bool,
}

/// What a mouse button does in the window.
pub enum Pointer {
    /// Capture the host mouse for the 1351.
    Capture,
    /// Release it.
    Release,
    /// Button of the paddles or of the mouse.
    Button(Button, bool),
    /// Click on the status bar, in bar coordinates.
    Bar(usize, usize),
    Nothing,
}

/// The host mouse in the window, for the paddles and the 1351 mouse in the
/// control ports.
///
/// - Paddles: the pointer stays visible and its position over the C64
///   screen is the position of the knobs (`paddles_at`); the left and right
///   buttons, pressed over the screen, are the fire buttons.
/// - 1351 mouse: a click on the C64 screen captures the host mouse (cursor
///   hidden and locked in the window) and its raw movement, converted to C64
///   pixels, moves the mouse (and any paddles); the middle button, the Cmd
///   key (Windows/Super key on the other systems) or leaving the window
///   releases it.
#[derive(Default)]
pub struct MouseCapture {
    captured: bool,
    /// Paddle fire buttons held down (bit 0 left, bit 1 right), released
    /// wherever the pointer is.
    held: u8,
    /// Movement not yet taken, in C64 pixels (fractions kept).
    dx: f64,
    dy: f64,
}

impl MouseCapture {
    /// Key that releases the mouse: Cmd on macOS, Windows/Super elsewhere
    /// (no C64 key is mapped to it; trackpads have no middle button).
    pub fn is_release_key(code: KeyCode) -> bool {
        matches!(code, KeyCode::SuperLeft | KeyCode::SuperRight)
    }

    pub fn captured(&self) -> bool {
        self.captured
    }

    /// Mouse button `button` pressed or released with the pointer at `at`
    /// (image coordinates, see `Placement::to_image_signed`, with a screen
    /// of `rows` lines).
    pub fn button(&mut self, button: MouseButton, pressed: bool, at: Option<(i32, i32)>, analog: Analog, rows: usize) -> Pointer {
        let which = match button {
            MouseButton::Left => Some((Button::Left, 1)),
            MouseButton::Right => Some((Button::Right, 2)),
            _ => None,
        };
        if self.captured {
            return match (which, button) {
                (Some((b, _)), _) => Pointer::Button(b, pressed),
                (None, MouseButton::Middle) if pressed => Pointer::Release,
                _ => Pointer::Nothing,
            };
        }
        let Some((b, bit)) = which else { return Pointer::Nothing };
        if !pressed {
            if self.held & bit != 0 {
                self.held &= !bit;
                return Pointer::Button(b, false);
            }
            return Pointer::Nothing;
        }
        let Some((x, y)) = at else { return Pointer::Nothing };
        let on_screen = (0..WIDTH as i32).contains(&x) && (0..rows as i32).contains(&y);
        if on_screen && analog.mouse {
            return if b == Button::Left { Pointer::Capture } else { Pointer::Nothing };
        }
        if on_screen && analog.paddles {
            self.held |= bit;
            return Pointer::Button(b, true);
        }
        let in_bar = (0..WIDTH as i32).contains(&x) && (rows as i32..(rows + super::status::BAR_HEIGHT) as i32).contains(&y);
        if in_bar && b == Button::Left {
            return Pointer::Bar(x as usize, y as usize - rows);
        }
        Pointer::Nothing
    }

    /// Pointer moved to `at`: the position for the paddles, when they are
    /// driven by the pointer (not captured) and it is not over the bar.
    pub fn paddles_at(&self, at: Option<(i32, i32)>, analog: Analog, rows: usize) -> Option<(i32, i32)> {
        let (x, y) = at?;
        (analog.paddles && !self.captured && y < rows as i32).then_some((x, y))
    }

    /// Hides and locks the cursor; false if the system does not allow it.
    pub fn capture(&mut self, window: &Window) -> bool {
        let ok = window.set_cursor_grab(CursorGrabMode::Locked)
            .or_else(|_| window.set_cursor_grab(CursorGrabMode::Confined))
            .is_ok();
        if ok {
            window.set_cursor_visible(false);
            self.captured = true;
            self.dx = 0.0;
            self.dy = 0.0;
        }
        ok
    }

    pub fn release(&mut self, window: &Window) {
        if self.captured {
            let _ = window.set_cursor_grab(CursorGrabMode::None);
            window.set_cursor_visible(true);
            self.captured = false;
        }
    }

    /// Raw movement (`DeviceEvent::MouseMotion`, in logical points) with the
    /// screen drawn as in `placement`.
    pub fn motion(&mut self, dx: f64, dy: f64, window: &Window, placement: &Placement) {
        let Rect { sx, sy, .. } = placement.screen;
        if self.captured && sx > 0.0 {
            let k = window.scale_factor();
            self.dx += dx * k / sx;
            self.dy += dy * k / sy;
        }
    }

    /// Whole C64 pixels moved since the last call.
    pub fn take(&mut self) -> (i32, i32) {
        let (x, y) = (self.dx.trunc(), self.dy.trunc());
        self.dx -= x;
        self.dy -= y;
        (x as i32, y as i32)
    }
}
