// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 SampoSoft - Francesco Sampoli

//! winit-specific parts, shared by `c64` and `c64dbg --window`: physical key
//! mapping, window attributes and icon, scaled drawing of the framebuffer
//! with the status bar below it, capture of the host mouse for the paddles
//! and the 1351 mouse.

use winit::dpi::LogicalSize;
use winit::event::MouseButton;
use winit::keyboard::{KeyCode, PhysicalKey};
use winit::window::{CursorGrabMode, Icon, Window, WindowAttributes};

use crate::ctrlport::Button;
use crate::keyboard::HostKey;
use crate::vic::{HEIGHT, WIDTH};

/// Identifier of a physical key, to pair the release of a printable key
/// with the character its press produced (`KeyMatrix::char_down/char_up`).
pub fn key_id(key: &PhysicalKey) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    key.hash(&mut h);
    h.finish()
}

/// Maps winit physical keys to non-printable host keys.
pub fn host_key(code: KeyCode) -> Option<HostKey> {
    Some(match code {
        KeyCode::Backspace => HostKey::Backspace,
        KeyCode::Delete => HostKey::Delete,
        KeyCode::Enter | KeyCode::NumpadEnter => HostKey::Return,
        KeyCode::Tab => HostKey::Tab,
        KeyCode::Escape => HostKey::Escape,
        KeyCode::Space => HostKey::Space,
        KeyCode::Home => HostKey::Home,
        KeyCode::ArrowLeft => HostKey::Left,
        KeyCode::ArrowRight => HostKey::Right,
        KeyCode::ArrowUp => HostKey::Up,
        KeyCode::ArrowDown => HostKey::Down,
        KeyCode::F1 => HostKey::F1,   KeyCode::F2 => HostKey::F2,
        KeyCode::F3 => HostKey::F3,   KeyCode::F4 => HostKey::F4,
        KeyCode::F5 => HostKey::F5,   KeyCode::F6 => HostKey::F6,
        KeyCode::F7 => HostKey::F7,   KeyCode::F8 => HostKey::F8,
        KeyCode::F9 => HostKey::F9,   KeyCode::F10 => HostKey::F10,
        KeyCode::F11 => HostKey::F11, KeyCode::F12 => HostKey::F12,
        KeyCode::ShiftLeft => HostKey::LShift,
        KeyCode::ShiftRight => HostKey::RShift,
        KeyCode::ControlLeft => HostKey::LCtrl,
        KeyCode::ControlRight => HostKey::RCtrl,
        KeyCode::AltLeft => HostKey::LAlt,
        KeyCode::AltRight => HostKey::RAlt,
        _ => return None,
    })
}

/// Window attributes: 2x the VIC resolution plus the status bar, at least
/// 1x.
pub fn window_attributes(title: &str) -> WindowAttributes {
    let h = HEIGHT + super::status::BAR_HEIGHT;
    winit::window::Window::default_attributes()
        .with_title(title)
        .with_inner_size(LogicalSize::new((WIDTH * 2) as f64, (h * 2) as f64))
        .with_min_inner_size(LogicalSize::new(WIDTH as f64, h as f64))
}

/// Application icon, generated by `tools/make_icon.py`.
const ICON_PNG: &[u8] = include_bytes!("../../assets/icon.png");
const ICON_RGBA: &[u8] = include_bytes!("../../assets/icon64.rgba");
const ICON_RGBA_SIDE: u32 = 64;

/// Sets the application icon: on the window (Windows, X11; Wayland uses
/// the one from the .desktop file) and in the Dock on macOS, where winit
/// ignores the window icon. To be called on the main thread.
pub fn set_app_icon(window: &Window) {
    if let Ok(icon) = Icon::from_rgba(ICON_RGBA.to_vec(), ICON_RGBA_SIDE, ICON_RGBA_SIDE) {
        window.set_window_icon(Some(icon));
    }
    #[cfg(target_os = "macos")]
    {
        use objc2::rc::Retained;
        use objc2::ClassType;
        use objc2_app_kit::{NSApplication, NSImage};
        use objc2_foundation::{MainThreadMarker, NSData};

        let Some(mtm) = MainThreadMarker::new() else { return };
        let data = NSData::with_bytes(ICON_PNG);
        let image: Option<Retained<NSImage>> = NSImage::initWithData(NSImage::alloc(), &data);
        if let Some(image) = image {
            let app = NSApplication::sharedApplication(mtm);
            // SAFETY: valid image, called on the main thread
            unsafe { app.setApplicationIconImage(Some(&image)) };
        }
    }
    #[cfg(not(target_os = "macos"))]
    let _ = ICON_PNG;
}

/// Position of the image in the window: corner and integer scale.
#[derive(Clone, Copy, Default)]
pub struct Placement {
    pub x0: usize,
    pub y0: usize,
    pub scale: usize,
}

impl Placement {
    /// Window point (physical pixels) in C64 pixels, from the top-left
    /// corner of the image; None outside the image.
    pub fn to_image(&self, x: f64, y: f64) -> Option<(usize, usize)> {
        if self.scale == 0 || x < self.x0 as f64 || y < self.y0 as f64 {
            return None;
        }
        Some(((x as usize - self.x0) / self.scale, (y as usize - self.y0) / self.scale))
    }

    /// Like `to_image`, but also outside the image (negative or beyond the
    /// edges); None only before the first drawing.
    pub fn to_image_signed(&self, x: f64, y: f64) -> Option<(i32, i32)> {
        if self.scale == 0 {
            return None;
        }
        let s = self.scale as f64;
        Some((((x - self.x0 as f64) / s).floor() as i32, ((y - self.y0 as f64) / s).floor() as i32))
    }
}

/// Copies the `layers` images (WIDTH wide, one below the other: the VIC
/// screen and the status bar) into `buf` (dw×dh) with integer
/// nearest-neighbour scaling, centered, on a black background.
pub fn blit_scaled(buf: &mut [u32], dw: usize, dh: usize, layers: &[&[u32]]) -> Placement {
    let height: usize = layers.iter().map(|l| l.len() / WIDTH).sum();
    let scale = (dw / WIDTH).min(dh / height).max(1);
    let (sw, sh) = (WIDTH * scale, height * scale);
    let x0 = dw.saturating_sub(sw) / 2;
    let y0 = dh.saturating_sub(sh) / 2;
    buf.fill(0);
    let rows = layers.iter().flat_map(|l| l.chunks_exact(WIDTH));
    for (sy, src) in rows.enumerate() {
        for y in sy * scale..(sy + 1) * scale {
            if y0 + y >= dh {
                return Placement { x0, y0, scale };
            }
            let dst = &mut buf[(y0 + y) * dw + x0..(y0 + y) * dw + x0 + sw.min(dw - x0)];
            for (x, px) in dst.iter_mut().enumerate() {
                *px = src[x / scale] & 0x00FF_FFFF;
            }
        }
    }
    Placement { x0, y0, scale }
}

/// Devices in the control ports that the window drives with the host mouse.
#[derive(Clone, Copy, Default)]
pub struct Analog {
    pub paddles: bool,
    pub mouse: bool,
}

/// What a mouse button does in the window.
pub enum Pointer {
    /// Capture the host mouse for the 1351.
    Capture,
    /// Release it.
    Release,
    /// Button of the paddles or of the mouse.
    Button(Button, bool),
    /// Click on the status bar, in bar coordinates.
    Bar(usize, usize),
    Nothing,
}

/// The host mouse in the window, for the paddles and the 1351 mouse in the
/// control ports.
///
/// - Paddles: the pointer stays visible and its position over the C64
///   screen is the position of the knobs (`paddles_at`); the left and right
///   buttons, pressed over the screen, are the fire buttons.
/// - 1351 mouse: a click on the C64 screen captures the host mouse (cursor
///   hidden and locked in the window) and its raw movement, converted to C64
///   pixels, moves the mouse (and any paddles); the middle button, the Cmd
///   key (Windows/Super key on the other systems) or leaving the window
///   releases it.
#[derive(Default)]
pub struct MouseCapture {
    captured: bool,
    /// Paddle fire buttons held down (bit 0 left, bit 1 right), released
    /// wherever the pointer is.
    held: u8,
    /// Movement not yet taken, in C64 pixels (fractions kept).
    dx: f64,
    dy: f64,
}

impl MouseCapture {
    /// Key that releases the mouse: Cmd on macOS, Windows/Super elsewhere
    /// (no C64 key is mapped to it; trackpads have no middle button).
    pub fn is_release_key(code: KeyCode) -> bool {
        matches!(code, KeyCode::SuperLeft | KeyCode::SuperRight)
    }

    pub fn captured(&self) -> bool {
        self.captured
    }

    /// Mouse button `button` pressed or released with the pointer at `at`
    /// (image coordinates, see `Placement::to_image_signed`).
    pub fn button(&mut self, button: MouseButton, pressed: bool, at: Option<(i32, i32)>, analog: Analog) -> Pointer {
        let which = match button {
            MouseButton::Left => Some((Button::Left, 1)),
            MouseButton::Right => Some((Button::Right, 2)),
            _ => None,
        };
        if self.captured {
            return match (which, button) {
                (Some((b, _)), _) => Pointer::Button(b, pressed),
                (None, MouseButton::Middle) if pressed => Pointer::Release,
                _ => Pointer::Nothing,
            };
        }
        let Some((b, bit)) = which else { return Pointer::Nothing };
        if !pressed {
            if self.held & bit != 0 {
                self.held &= !bit;
                return Pointer::Button(b, false);
            }
            return Pointer::Nothing;
        }
        let Some((x, y)) = at else { return Pointer::Nothing };
        let on_screen = (0..WIDTH as i32).contains(&x) && (0..HEIGHT as i32).contains(&y);
        if on_screen && analog.mouse {
            return if b == Button::Left { Pointer::Capture } else { Pointer::Nothing };
        }
        if on_screen && analog.paddles {
            self.held |= bit;
            return Pointer::Button(b, true);
        }
        let in_bar = (0..WIDTH as i32).contains(&x) && (HEIGHT as i32..(HEIGHT + super::status::BAR_HEIGHT) as i32).contains(&y);
        if in_bar && b == Button::Left {
            return Pointer::Bar(x as usize, y as usize - HEIGHT);
        }
        Pointer::Nothing
    }

    /// Pointer moved to `at`: the position for the paddles, when they are
    /// driven by the pointer (not captured) and it is not over the bar.
    pub fn paddles_at(&self, at: Option<(i32, i32)>, analog: Analog) -> Option<(i32, i32)> {
        let (x, y) = at?;
        (analog.paddles && !self.captured && y < HEIGHT as i32).then_some((x, y))
    }

    /// Hides and locks the cursor; false if the system does not allow it.
    pub fn capture(&mut self, window: &Window) -> bool {
        let ok = window.set_cursor_grab(CursorGrabMode::Locked)
            .or_else(|_| window.set_cursor_grab(CursorGrabMode::Confined))
            .is_ok();
        if ok {
            window.set_cursor_visible(false);
            self.captured = true;
            self.dx = 0.0;
            self.dy = 0.0;
        }
        ok
    }

    pub fn release(&mut self, window: &Window) {
        if self.captured {
            let _ = window.set_cursor_grab(CursorGrabMode::None);
            window.set_cursor_visible(true);
            self.captured = false;
        }
    }

    /// Raw movement (`DeviceEvent::MouseMotion`, in logical points) with the
    /// image drawn at `scale` physical pixels per C64 pixel.
    pub fn motion(&mut self, dx: f64, dy: f64, window: &Window, scale: usize) {
        if self.captured {
            let k = window.scale_factor() / scale.max(1) as f64;
            self.dx += dx * k;
            self.dy += dy * k;
        }
    }

    /// Whole C64 pixels moved since the last call.
    pub fn take(&mut self) -> (i32, i32) {
        let (x, y) = (self.dx.trunc(), self.dy.trunc());
        self.dx -= x;
        self.dy -= y;
        (x as i32, y as i32)
    }
}
