// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 SampoSoft - Francesco Sampoli

//! 6510 disassembler: complete table of the 256 opcodes (legal and illegal).
//! Generated by tools/gen_disasm.py — do not edit by hand.

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode { Imp, Acc, Imm, Zp, Zpx, Zpy, Abs, Abx, Aby, Ind, Izx, Izy, Rel }

impl Mode {
    /// Total instruction length in bytes (opcode included).
    pub fn len(self) -> u16 {
        match self {
            Mode::Imp | Mode::Acc => 1,
            Mode::Imm | Mode::Zp | Mode::Zpx | Mode::Zpy | Mode::Izx | Mode::Izy | Mode::Rel => 2,
            Mode::Abs | Mode::Abx | Mode::Aby | Mode::Ind => 3,
        }
    }
}

/// (mnemonic, mode, illegal)
pub static OPCODES: [(&str, Mode, bool); 256] = [
    ("BRK", Mode::Imp, false), // $00
    ("ORA", Mode::Izx, false), // $01
    ("KIL", Mode::Imp, true ), // $02
    ("SLO", Mode::Izx, true ), // $03
    ("NOP", Mode::Zp, true ), // $04
    ("ORA", Mode::Zp, false), // $05
    ("ASL", Mode::Zp, false), // $06
    ("SLO", Mode::Zp, true ), // $07
    ("PHP", Mode::Imp, false), // $08
    ("ORA", Mode::Imm, false), // $09
    ("ASL", Mode::Acc, false), // $0A
    ("ANC", Mode::Imm, true ), // $0B
    ("NOP", Mode::Abs, true ), // $0C
    ("ORA", Mode::Abs, false), // $0D
    ("ASL", Mode::Abs, false), // $0E
    ("SLO", Mode::Abs, true ), // $0F
    ("BPL", Mode::Rel, false), // $10
    ("ORA", Mode::Izy, false), // $11
    ("KIL", Mode::Imp, true ), // $12
    ("SLO", Mode::Izy, true ), // $13
    ("NOP", Mode::Zpx, true ), // $14
    ("ORA", Mode::Zpx, false), // $15
    ("ASL", Mode::Zpx, false), // $16
    ("SLO", Mode::Zpx, true ), // $17
    ("CLC", Mode::Imp, false), // $18
    ("ORA", Mode::Aby, false), // $19
    ("NOP", Mode::Imp, true ), // $1A
    ("SLO", Mode::Aby, true ), // $1B
    ("NOP", Mode::Abx, true ), // $1C
    ("ORA", Mode::Abx, false), // $1D
    ("ASL", Mode::Abx, false), // $1E
    ("SLO", Mode::Abx, true ), // $1F
    ("JSR", Mode::Abs, false), // $20
    ("AND", Mode::Izx, false), // $21
    ("KIL", Mode::Imp, true ), // $22
    ("RLA", Mode::Izx, true ), // $23
    ("BIT", Mode::Zp, false), // $24
    ("AND", Mode::Zp, false), // $25
    ("ROL", Mode::Zp, false), // $26
    ("RLA", Mode::Zp, true ), // $27
    ("PLP", Mode::Imp, false), // $28
    ("AND", Mode::Imm, false), // $29
    ("ROL", Mode::Acc, false), // $2A
    ("ANC", Mode::Imm, true ), // $2B
    ("BIT", Mode::Abs, false), // $2C
    ("AND", Mode::Abs, false), // $2D
    ("ROL", Mode::Abs, false), // $2E
    ("RLA", Mode::Abs, true ), // $2F
    ("BMI", Mode::Rel, false), // $30
    ("AND", Mode::Izy, false), // $31
    ("KIL", Mode::Imp, true ), // $32
    ("RLA", Mode::Izy, true ), // $33
    ("NOP", Mode::Zpx, true ), // $34
    ("AND", Mode::Zpx, false), // $35
    ("ROL", Mode::Zpx, false), // $36
    ("RLA", Mode::Zpx, true ), // $37
    ("SEC", Mode::Imp, false), // $38
    ("AND", Mode::Aby, false), // $39
    ("NOP", Mode::Imp, true ), // $3A
    ("RLA", Mode::Aby, true ), // $3B
    ("NOP", Mode::Abx, true ), // $3C
    ("AND", Mode::Abx, false), // $3D
    ("ROL", Mode::Abx, false), // $3E
    ("RLA", Mode::Abx, true ), // $3F
    ("RTI", Mode::Imp, false), // $40
    ("EOR", Mode::Izx, false), // $41
    ("KIL", Mode::Imp, true ), // $42
    ("SRE", Mode::Izx, true ), // $43
    ("NOP", Mode::Zp, true ), // $44
    ("EOR", Mode::Zp, false), // $45
    ("LSR", Mode::Zp, false), // $46
    ("SRE", Mode::Zp, true ), // $47
    ("PHA", Mode::Imp, false), // $48
    ("EOR", Mode::Imm, false), // $49
    ("LSR", Mode::Acc, false), // $4A
    ("ALR", Mode::Imm, true ), // $4B
    ("JMP", Mode::Abs, false), // $4C
    ("EOR", Mode::Abs, false), // $4D
    ("LSR", Mode::Abs, false), // $4E
    ("SRE", Mode::Abs, true ), // $4F
    ("BVC", Mode::Rel, false), // $50
    ("EOR", Mode::Izy, false), // $51
    ("KIL", Mode::Imp, true ), // $52
    ("SRE", Mode::Izy, true ), // $53
    ("NOP", Mode::Zpx, true ), // $54
    ("EOR", Mode::Zpx, false), // $55
    ("LSR", Mode::Zpx, false), // $56
    ("SRE", Mode::Zpx, true ), // $57
    ("CLI", Mode::Imp, false), // $58
    ("EOR", Mode::Aby, false), // $59
    ("NOP", Mode::Imp, true ), // $5A
    ("SRE", Mode::Aby, true ), // $5B
    ("NOP", Mode::Abx, true ), // $5C
    ("EOR", Mode::Abx, false), // $5D
    ("LSR", Mode::Abx, false), // $5E
    ("SRE", Mode::Abx, true ), // $5F
    ("RTS", Mode::Imp, false), // $60
    ("ADC", Mode::Izx, false), // $61
    ("KIL", Mode::Imp, true ), // $62
    ("RRA", Mode::Izx, true ), // $63
    ("NOP", Mode::Zp, true ), // $64
    ("ADC", Mode::Zp, false), // $65
    ("ROR", Mode::Zp, false), // $66
    ("RRA", Mode::Zp, true ), // $67
    ("PLA", Mode::Imp, false), // $68
    ("ADC", Mode::Imm, false), // $69
    ("ROR", Mode::Acc, false), // $6A
    ("ARR", Mode::Imm, true ), // $6B
    ("JMP", Mode::Ind, false), // $6C
    ("ADC", Mode::Abs, false), // $6D
    ("ROR", Mode::Abs, false), // $6E
    ("RRA", Mode::Abs, true ), // $6F
    ("BVS", Mode::Rel, false), // $70
    ("ADC", Mode::Izy, false), // $71
    ("KIL", Mode::Imp, true ), // $72
    ("RRA", Mode::Izy, true ), // $73
    ("NOP", Mode::Zpx, true ), // $74
    ("ADC", Mode::Zpx, false), // $75
    ("ROR", Mode::Zpx, false), // $76
    ("RRA", Mode::Zpx, true ), // $77
    ("SEI", Mode::Imp, false), // $78
    ("ADC", Mode::Aby, false), // $79
    ("NOP", Mode::Imp, true ), // $7A
    ("RRA", Mode::Aby, true ), // $7B
    ("NOP", Mode::Abx, true ), // $7C
    ("ADC", Mode::Abx, false), // $7D
    ("ROR", Mode::Abx, false), // $7E
    ("RRA", Mode::Abx, true ), // $7F
    ("NOP", Mode::Imm, true ), // $80
    ("STA", Mode::Izx, false), // $81
    ("NOP", Mode::Imm, true ), // $82
    ("SAX", Mode::Izx, true ), // $83
    ("STY", Mode::Zp, false), // $84
    ("STA", Mode::Zp, false), // $85
    ("STX", Mode::Zp, false), // $86
    ("SAX", Mode::Zp, true ), // $87
    ("DEY", Mode::Imp, false), // $88
    ("NOP", Mode::Imm, true ), // $89
    ("TXA", Mode::Imp, false), // $8A
    ("XAA", Mode::Imm, true ), // $8B
    ("STY", Mode::Abs, false), // $8C
    ("STA", Mode::Abs, false), // $8D
    ("STX", Mode::Abs, false), // $8E
    ("SAX", Mode::Abs, true ), // $8F
    ("BCC", Mode::Rel, false), // $90
    ("STA", Mode::Izy, false), // $91
    ("KIL", Mode::Imp, true ), // $92
    ("AHX", Mode::Izy, true ), // $93
    ("STY", Mode::Zpx, false), // $94
    ("STA", Mode::Zpx, false), // $95
    ("STX", Mode::Zpy, false), // $96
    ("SAX", Mode::Zpy, true ), // $97
    ("TYA", Mode::Imp, false), // $98
    ("STA", Mode::Aby, false), // $99
    ("TXS", Mode::Imp, false), // $9A
    ("TAS", Mode::Aby, true ), // $9B
    ("SHY", Mode::Abx, true ), // $9C
    ("STA", Mode::Abx, false), // $9D
    ("SHX", Mode::Aby, true ), // $9E
    ("AHX", Mode::Aby, true ), // $9F
    ("LDY", Mode::Imm, false), // $A0
    ("LDA", Mode::Izx, false), // $A1
    ("LDX", Mode::Imm, false), // $A2
    ("LAX", Mode::Izx, true ), // $A3
    ("LDY", Mode::Zp, false), // $A4
    ("LDA", Mode::Zp, false), // $A5
    ("LDX", Mode::Zp, false), // $A6
    ("LAX", Mode::Zp, true ), // $A7
    ("TAY", Mode::Imp, false), // $A8
    ("LDA", Mode::Imm, false), // $A9
    ("TAX", Mode::Imp, false), // $AA
    ("LAX", Mode::Imm, true ), // $AB
    ("LDY", Mode::Abs, false), // $AC
    ("LDA", Mode::Abs, false), // $AD
    ("LDX", Mode::Abs, false), // $AE
    ("LAX", Mode::Abs, true ), // $AF
    ("BCS", Mode::Rel, false), // $B0
    ("LDA", Mode::Izy, false), // $B1
    ("KIL", Mode::Imp, true ), // $B2
    ("LAX", Mode::Izy, true ), // $B3
    ("LDY", Mode::Zpx, false), // $B4
    ("LDA", Mode::Zpx, false), // $B5
    ("LDX", Mode::Zpy, false), // $B6
    ("LAX", Mode::Zpy, true ), // $B7
    ("CLV", Mode::Imp, false), // $B8
    ("LDA", Mode::Aby, false), // $B9
    ("TSX", Mode::Imp, false), // $BA
    ("LAS", Mode::Aby, true ), // $BB
    ("LDY", Mode::Abx, false), // $BC
    ("LDA", Mode::Abx, false), // $BD
    ("LDX", Mode::Aby, false), // $BE
    ("LAX", Mode::Aby, true ), // $BF
    ("CPY", Mode::Imm, false), // $C0
    ("CMP", Mode::Izx, false), // $C1
    ("NOP", Mode::Imm, true ), // $C2
    ("DCP", Mode::Izx, true ), // $C3
    ("CPY", Mode::Zp, false), // $C4
    ("CMP", Mode::Zp, false), // $C5
    ("DEC", Mode::Zp, false), // $C6
    ("DCP", Mode::Zp, true ), // $C7
    ("INY", Mode::Imp, false), // $C8
    ("CMP", Mode::Imm, false), // $C9
    ("DEX", Mode::Imp, false), // $CA
    ("SBX", Mode::Imm, true ), // $CB
    ("CPY", Mode::Abs, false), // $CC
    ("CMP", Mode::Abs, false), // $CD
    ("DEC", Mode::Abs, false), // $CE
    ("DCP", Mode::Abs, true ), // $CF
    ("BNE", Mode::Rel, false), // $D0
    ("CMP", Mode::Izy, false), // $D1
    ("KIL", Mode::Imp, true ), // $D2
    ("DCP", Mode::Izy, true ), // $D3
    ("NOP", Mode::Zpx, true ), // $D4
    ("CMP", Mode::Zpx, false), // $D5
    ("DEC", Mode::Zpx, false), // $D6
    ("DCP", Mode::Zpx, true ), // $D7
    ("CLD", Mode::Imp, false), // $D8
    ("CMP", Mode::Aby, false), // $D9
    ("NOP", Mode::Imp, true ), // $DA
    ("DCP", Mode::Aby, true ), // $DB
    ("NOP", Mode::Abx, true ), // $DC
    ("CMP", Mode::Abx, false), // $DD
    ("DEC", Mode::Abx, false), // $DE
    ("DCP", Mode::Abx, true ), // $DF
    ("CPX", Mode::Imm, false), // $E0
    ("SBC", Mode::Izx, false), // $E1
    ("NOP", Mode::Imm, true ), // $E2
    ("ISC", Mode::Izx, true ), // $E3
    ("CPX", Mode::Zp, false), // $E4
    ("SBC", Mode::Zp, false), // $E5
    ("INC", Mode::Zp, false), // $E6
    ("ISC", Mode::Zp, true ), // $E7
    ("INX", Mode::Imp, false), // $E8
    ("SBC", Mode::Imm, false), // $E9
    ("NOP", Mode::Imp, false), // $EA
    ("SBC", Mode::Imm, true ), // $EB
    ("CPX", Mode::Abs, false), // $EC
    ("SBC", Mode::Abs, false), // $ED
    ("INC", Mode::Abs, false), // $EE
    ("ISC", Mode::Abs, true ), // $EF
    ("BEQ", Mode::Rel, false), // $F0
    ("SBC", Mode::Izy, false), // $F1
    ("KIL", Mode::Imp, true ), // $F2
    ("ISC", Mode::Izy, true ), // $F3
    ("NOP", Mode::Zpx, true ), // $F4
    ("SBC", Mode::Zpx, false), // $F5
    ("INC", Mode::Zpx, false), // $F6
    ("ISC", Mode::Zpx, true ), // $F7
    ("SED", Mode::Imp, false), // $F8
    ("SBC", Mode::Aby, false), // $F9
    ("NOP", Mode::Imp, true ), // $FA
    ("ISC", Mode::Aby, true ), // $FB
    ("NOP", Mode::Abx, true ), // $FC
    ("SBC", Mode::Abx, false), // $FD
    ("INC", Mode::Abx, false), // $FE
    ("ISC", Mode::Abx, true ), // $FF
];

/// Base cycles of each opcode (without the extra cycle for page cross or
/// taken branch). The instruction's memory access happens in the last one.
pub static BASE_CYCLES: [u8; 256] = [
    7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6, // $00
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, // $10
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6, // $20
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, // $30
    6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6, // $40
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, // $50
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6, // $60
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, // $70
    2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4, // $80
    2, 6, 2, 6, 4, 4, 4, 4, 2, 5, 2, 5, 5, 5, 5, 5, // $90
    2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4, // $A0
    2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4, // $B0
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, // $C0
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, // $D0
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, // $E0
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, // $F0
];


/// Disassembled instruction.
pub struct Instr {
    pub addr: u16,
    pub bytes: Vec<u8>,
    pub mnemonic: &'static str,
    pub operand: String,
    pub illegal: bool,
}

impl Instr {
    pub fn len(&self) -> u16 { self.bytes.len() as u16 }

    /// Hex bytes separated by spaces, e.g. "A5 C6".
    pub fn bytes_hex(&self) -> String {
        self.bytes.iter().map(|b| format!("{b:02X}")).collect::<Vec<_>>().join(" ")
    }

    /// "LDA $C6" (mnemonic + operand). Illegal opcodes are in lowercase.
    pub fn text(&self) -> String {
        let m = if self.illegal { self.mnemonic.to_ascii_lowercase() } else { self.mnemonic.to_string() };
        if self.operand.is_empty() { m } else { format!("{m} {}", self.operand) }
    }
}

/// Disassembles the instruction at `pc` using `peek` (side-effect-free read).
pub fn disasm(peek: &dyn Fn(u16) -> u8, pc: u16) -> Instr {
    let op = peek(pc);
    let (mnemonic, mode, illegal) = OPCODES[op as usize];
    let len = mode.len();
    let bytes: Vec<u8> = (0..len).map(|i| peek(pc.wrapping_add(i))).collect();
    let b1 = bytes.get(1).copied().unwrap_or(0);
    let b2 = bytes.get(2).copied().unwrap_or(0);
    let w = u16::from_le_bytes([b1, b2]);
    let operand = match mode {
        Mode::Imp => String::new(),
        Mode::Acc => "A".to_string(),
        Mode::Imm => format!("#${b1:02X}"),
        Mode::Zp  => format!("${b1:02X}"),
        Mode::Zpx => format!("${b1:02X},X"),
        Mode::Zpy => format!("${b1:02X},Y"),
        Mode::Abs => format!("${w:04X}"),
        Mode::Abx => format!("${w:04X},X"),
        Mode::Aby => format!("${w:04X},Y"),
        Mode::Ind => format!("(${w:04X})"),
        Mode::Izx => format!("(${b1:02X},X)"),
        Mode::Izy => format!("(${b1:02X}),Y"),
        Mode::Rel => {
            let target = pc.wrapping_add(2).wrapping_add(b1 as i8 as u16);
            format!("${target:04X}")
        }
    };
    Instr { addr: pc, bytes, mnemonic, operand, illegal }
}
